### ISSUE TITLE
Plotting IsoQuant Results similar to SQNTI3?

### ISSUE THREAD

**Issue by unique379r** [ablab/IsoQuant#104]
Hi
I am wondering if somehow i can plot the results of IsoQuant similar to SQANTI3? That could be the better way of interpreting the results ?

Thanks

**Comment by andrewprzh** [comment]
Dear @unique379r 

Unfortunately IsoQuant does not provide any graphical report at the moment. The best way would probably be run the latest SQANTI on IsoQuant `transcript_models.gtf`. As far as I know SQANTI now supports GTF files as input.

Best
Andrey
