### ISSUE TITLE
Strand issues for several novel genes in GTF (".", not "+" or "-")

### ISSUE THREAD

**Issue by jjuhyunkim** [ablab/IsoQuant#107]
Hi, 

I encountered an error stating `assert strand == '+' or strand == '-'` while running `sqanti3_qc.py`. Additionally, I noticed several novel genes with a strand designation of "." in the 7th column in `transcript_models.gtf` (figure below)

These genes are not mono-exonic. 
I utilized the most recent version of isoquant (v3.3.1)
<img width="968" alt="Screenshot 2023-08-22 at 3 24 34 PM" src="https://github.com/ablab/IsoQuant/assets/131193680/5f160f66-a73f-4726-b3d6-1f263f2b0028">

I have notice that similar issues in the past, and you addressed them in a previous version.
 However, the problem persists. 
Could you assist me in identifying the underlying cause of this issue? 

Thank you! : )
JH

**Comment by andrewprzh** [comment]
Dear @Juhyun-Kim-0203

I suspect that these transcripts may not have any canonical splice sites, and thus their strand cannot be determined. 
Could you tell which genome you are using? Also, I would be helpful if you could share a small subset of reads that map these transcripts. Is it possbile?

Probably, I should also make an option for filtering out such "unreliable" transcript predictions.

Best
Andrey

**Comment by Juhyun-Kim-0203** [comment]
Dear Andrey

Thank you for your rapid response!
Is it okay with hard masking?

Thank you!
Juhyun

2023년 8월 31일 (목) 오후 12:03, Andrey Prjibelski ***@***.***>님이
작성:

**Comment by andrewprzh** [comment]
Dear @Juhyun-Kim-0203 

For hard-masked genomes I presume minimap won't be able to map the reads and thus the transcript won't be discovered at all. However, if splice sites have "NN" characters the strand will be also reported as ".". 

Best
Andrey

**Comment by andrewprzh** [comment]
Finally released new [version 3.4](https://github.com/ablab/IsoQuant/releases/tag/v3.4.0), which fixes this issue.
