### ISSUE TITLE
how to compare gtf output from isoquant ?

### ISSUE THREAD

**Issue by unique379r** [ablab/IsoQuant#109]
Hi 
I have multiple samples output from Isoquant and want to compare the output across the samples. I am guessing, i should be using "SAMPLE_ID.transcript_models.gtf - GTF file with discovered expressed transcript (both known and novel transcripts)", right ?

Q: Do you suggest any tools that can take multiple sample gtf to compare not only by co-ordinates but also by features(gee, transcript id, exons etc) ?

Thanks

**Comment by andrewprzh** [comment]
Dear @unique379r 

I have used only [gffcompare](https://ccb.jhu.edu/software/stringtie/gffcompare.shtml), which compares GTFs only using coordinates. Unfortunately, I'm not aware of any ID-based comparison tools.

I'm not sure about your final goal, but it might help to create a joint GTF from all samples combined and use "per-sample" counts to figure out which isoforms/genes express in which samples.

Best
Andrey

**Comment by dawangran** [comment]
Hi~
I have multiple sample data and I run it separately, and I get multiple gtf files. I have found that the naming rules for new transcripts are random. I need to integrate a complete gtf without redundancy, what do I need to do? If I run multiple samples together with --bamlist, this method will consume a lot of time.

Thanks
