### ISSUE TITLE
isoquant results 

### ISSUE THREAD

**Issue by Nikhilgunala** [ablab/IsoQuant#119]
hi @andrewprzh 

 command : isoquant.py -d pacbio_ccs --fl_data --bam minimap2mappedsorted.bam   --reference chromosomes.fa  --output  isoquant  --threads 8  --transcript_quantification all --gene_quantification all --matching_strategy precise 

why  in the final trsncript_model.gtf file , only nnic transcripts are reported, how to get all transcripts not only novel  ??

<img width="642" alt="isoquantresults1" src="https://github.com/ablab/IsoQuant/assets/90795103/2fc094c8-b9da-412d-8d06-ce85ac58eec9">

results : 
229730 exon
  22475 gene
  30210 transcript

thank you in advance !!

**Comment by andrewprzh** [comment]
Dear @Nikhilgunala 

You are running IsoQuant in a annotation-free mode, thus every output transcript is classified as "novel not in catalog".
IsoQuant needs a reference annotation (provided via `--genedb`) to detect known or "novel in catalog" transcripts.

Best
Andrey

**Comment by Nikhilgunala** [comment]
thank you very much 
@andrewprzh

**Comment by Nikhilgunala** [comment]
Dear @andrewprzh

Please tell me, is there any way to count single exons also for pacbio flnc reads ?? 

thank you!
Nikhil

**Comment by andrewprzh** [comment]
@andrewprzh 

You may use `--count_exons` option, but in the current version it only works when the reference annotation is provided.

Best
Andrey
