### ISSUE TITLE
Isoform annotation

### ISSUE THREAD

**Issue by MiqG** [ablab/IsoQuant#120]
Hi, I was wondering what are the tools you recommend using to annotate resulting transcripts from your pipeline, that is annotating UTRs, ORF and even the possible proteoform sequences.

Thanks very much in advance,

Miquel

**Comment by andrewprzh** [comment]
Dear @MiqG 

Unfortunately, I don't have experience with transcript annotation. The only program that comes to mind is [Augustus](https://github.com/Gaius-Augustus/Augustus/blob/master/docs/ABOUT.md), but seems like it's rather a gene prediction tool, than something for annotation enhancement. 
I'll get back in case I come across anything interesting. 

Best
Andrey

**Comment by MiqG** [comment]
Thanks a lot @andrewprzh !

Actually, in case someone might be interested, upon opening this issue I asked around a bit more and I came across [SQANTI3](https://github.com/ConesaLab/SQANTI3) which contains the IsoAnnotLite module for de novo annotation of long-read transcripts. I haven't tried it out yet but it seems to do the job in their [article](https://doi.org/10.1101/2023.05.17.541248).

Thanks! Best,

Miquel

**Comment by andrewprzh** [comment]
@MiqG 

Thank you, I somehow forgot about this tool! If you ever come to launching them on IsoQuant output, let me know if there is something that would improve compatibility.

Best
Andrey

**Comment by MiqG** [comment]
Sounds good!

Cheers,
Miquel
