### ISSUE TITLE
ERROR running IsoQuant version 3.3.0

### ISSUE THREAD

**Issue by sparthib** [ablab/IsoQuant#122]
I get the following error while running IsoQuant 3.3.0:

`IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesTraceback (most recent call last):
  File "/users/sparthib/IsoQuant/isoquant.py", line 698, in <module>
    main(sys.argv[1:])
  File "/users/sparthib/IsoQuant/isoquant.py", line 689, in main
    args = check_and_load_args(args, parser)
  File "/users/sparthib/IsoQuant/isoquant.py", line 256, in check_and_load_args
    if not check_input_params(args):
  File "/users/sparthib/IsoQuant/isoquant.py", line 316, in check_input_params
    args.input_data = InputDataStorage(args)
  File "/users/sparthib/IsoQuant/src/input_data_storage.py", line 86, in __init__
    check_input_type(bam, self.input_type)
  File "/users/sparthib/IsoQuant/src/input_data_storage.py", line 189, in check_input_type
    raise Exception("File format " + fasta_ext + " is not supported! Supported formats: FASTQ, FASTA, BAM")
Exception: File format is not supported! Supported formats: FASTQ, FASTA, BAM`

I checked my file formats, my reference files were gzipped FASTA and GTF. My input file was a bam file. Isoquant did work on the test data provided. I am not sure what could be causing the error. Any help would be great, thanks!

**Comment by andrewprzh** [comment]
Dear @sparthib 

Could send full isoquant.log file please?

Best
Andrey

**Comment by andrewprzh** [comment]
Dear @sparthib 

Your reference genome and reference annotation have to end with .fasta/.fa and .gtf respectively (can also be gzipped) so IsoQuant can figure out the input format. Please, rename your files accordingly and try re-running it.

Best
Andrey

**Comment by sparthib** [comment]
Hi Andrey,

I renamed the files and I am still getting the same error. 
[isoquant.log](https://github.com/ablab/IsoQuant/files/13034658/isoquant.log)

**Comment by andrewprzh** [comment]
@sparthib 

This looks odd. Could you remove the output folder or restart with `--clean_start` option?

Best
Andrey

**Comment by sparthib** [comment]
I tried that and it works now, thanks!
