### ISSUE TITLE
Single Nuclei Intron Retention

### ISSUE THREAD

**Issue by atrull314** [ablab/IsoQuant#123]
Hi,

This tool has been great so far for our single cell analysis. We are looking to begin analysis for single-nuclei data as well. One thing we are unclear is whether or not intronic mapped reads are included in the counts produced by this pipeline? (Note we use the grouped_counts for our analyses)

I know that you are able to produce separate files for introns and exons, but curious about the base output files.

**Comment by andrewprzh** [comment]
Dear @atrull314 

Thanks for the feedback and sorry for the delayed reply!

Intronic reads and reads with intron retention (complete or partial), are reported as inconsistent, at thus are not included in transcripts counts. However, by the default, they are included in gene counts (if there is a single unambiguously assigned gene).
You may change these parameters using `--transcript_quantification` and `--gene_quantification`.

Also, as far as I know, single-nuclei data may feature internal polyA priming. This event is detected by IsoQuant and flagged as `internal_polya_left` or `internal_polya_right`. These reads are also considered as inconsistent and are treated the same way as the ones above.

Hope this helps, do not hesitate to ask more questions!

Best
Andrey
