### ISSUE TITLE
Reference genome or transcriptome? 

### ISSUE THREAD

**Issue by sparthib** [ablab/IsoQuant#125]
Hi, the instructions for IsoQuant asks to use a reference genome FASTA specifically. Would it not work for a reference transcriptome? Thanks!

**Comment by andrewprzh** [comment]
Dear @sparthib 

IsoQuant uses minimap2 and aims at transcriptome reconstruction by analyzing spliced alignments. So it won't work with transcriptome.

If you'd like to quantify you transcripts by using transcriptome FASTA, [NanoSim](https://github.com/bcgsc/NanoSim) has quantification function in it, look for `read_analysis.py transcriptome` and you will need `-q` option.

Hope this may be of use!

Best
Andrey

**Comment by sparthib** [comment]
thank you for the suggestion!
