### ISSUE TITLE
Performing shrinkage when running DeSeq2 on gene_counts.tsv

### ISSUE THREAD

**Issue by jamesbayne** [ablab/IsoQuant#126]
Hi there,

I am analysing RNA-seq data generated by cDNA sequencing on a promethION (basecalled with guppy). We have sequenced at very high depth (60-80M reads per sample) and I want to perform some differential expression analysis on the data.

After running IsoQuant (which appears to be working correctly) I then read the `gene_counts.tsv` files (I am only interested in mapping to genes, not isoforms). I then run DESeq2 with `DESeqDataSetFromMatrix` to create the dds object from the IsoQuant data.

There are 18 samples in the experiment and each of the samples has gone through the same pipeline. 

I find that the .tsv files have different numbers of lines, presumably because some genes from my reference genome are not detected in some of the samples but are in others. If a gene is missing from a given gene_counts.tsv but is present in another then I assign it a count of 0.

I am finding lots of lowly expressed genes (baseMean < 50) with log2FCs > 30 - even after shrinkage (using the ashr algorithm). I also have Illumina sequencing of the same samples and the log2FCs seem much more moderate. I was wondering if you know whether the ashr algorithm is applicable to ONT data and/or whether to just use a higher baseMean filter?

Thanks!

**Comment by andrewprzh** [comment]
Dear @jamesbayne 

Sorry for the delay.

To be honest, I don't have a lot of experience with DE analysis using ONT data and ashr algorithm.
In principle, it seems like it should not be much different from DE analysis using short reads, however, as you indicate - it is.  
You can send my 1-2 lines from gene counts table and read assignments related to these genes, I can try to have a look and check if everything is in tact.

>I find that the .tsv files have different numbers of lines, presumably because some genes from my reference genome are not detected in some of the samples but are in others. If a gene is missing from a given gene_counts.tsv but is present in another then I assign it a count of 0.

Just in case, you can provide multiple samples to IsoQuant and thus receive a gene count table with 18 columns.

Best
Andrey

**Comment by andrewprzh** [comment]
Please, re-open if you have further questions.
