### ISSUE TITLE
Problems about using short Illumina reads to correct long-read alignments

### ISSUE THREAD

**Issue by qingwangchen** [ablab/IsoQuant#129]
While using IsoQuant, I have encountered two questions that I hope you help. They are as follows

1. The latest release **IsoQuant v3.3.1 did not provide the parameter "--illumina_bam"**, although the ReadMe mentions that we can use short Illumina reads to correct long-read alignments through the parameter.
2. The parameter "--illumina_bam" of the master version (532f70af110632acd0feb7dc57abc12732424efa) of  **IsoQuant v3.3.0 did not work** when I tried to use the illumina_bam to correct the ONT alignment of the same samples. (The long&short outputs are the same as the long-only's)

How to solve this problem? Looking forward to your reply, thanks!

The test details can be seen at: 
[isoquant.log](https://github.com/ablab/IsoQuant/files/13660069/isoquant.log)

**Comment by andrewprzh** [comment]
Dear @qingwangchen 

`--illumina_bam` is still an experimental option and was not released yet. I will be out in 3.4.

By same output you imply that output GTFs are identical?

Best
Andrey

**Comment by qingwangchen** [comment]
> By same output you imply that output GTFs are identical?

Yes. The contents of the specified results directory are all identical, and the log files indicate that IsoQuant only uses ONT's long-read bam, even though I provided illumina_bam.

**Comment by qingwangchen** [comment]
Dear @andrewprzh 

When IsoQuant v3.4 will be released? Thanks😁

Best
Qingwang

**Comment by andrewprzh** [comment]
@qingwangchen 

The log is fine, there are currently no records with respect to Illumina BAM usage.
The contents of the output folders are also expected to be identical, but are the files identical byte-by-byte?

Best
Andrey

**Comment by andrewprzh** [comment]
We plant to release IsoQuant 3.4 within the next month, optimistically before the New Year.

**Comment by qingwangchen** [comment]
> @qingwangchen
> 
> The log is fine, there are currently no records with respect to Illumina BAM usage. The contents of the output folders are also expected to be identical, but are the files identical byte-by-byte?
> 
> Best Andrey

Dear @andrewprzh 

I did a quick check of the `*.extended_annotation.gtf` file and the `*.transcript_tpm.tsv`, the former files are not exactly the same byte-by-byte and the latter files are exactly the same.

Best
Qingwang

**Comment by qingwangchen** [comment]
> We plant to release IsoQuant 3.4 within the next month, optimistically before the New Year.

Hope all goes well and thanks for developing such a great tool for everyone to use.

**Comment by andrewprzh** [comment]
Dear @qingwangchen 

The count and TPM tables are expected to be the same. 
Illumina is used only for correcting splice site postilions in long read alignments, and thus affects only final GTFs (`transcipt_models.gtf` and `extended_annotation.gtf` )and `corrected_reads.bed` files.
If those are not identical (except the header that also contains a command line string), then it probably worked :)

Best
Andrey

**Comment by qingwangchen** [comment]
Dear @andrewprzh 

Thank you for your kind explanations. I figured it out. 

Further, I would like to inquire if even in the upcoming release of IsoQuant v3.4, the count and TPM tables won't be changed with the addition of Illumina bam? Even similar tools like Stingtie2 and Flair2 don't just correct splice site postilions in long read alignments through using Illumina bam, but also cause changes in quantitative results (Count and TPM).

Best
Qingwang

**Comment by andrewprzh** [comment]
Dear @qingwangchen 

Yes, we have a plan to incorporate Illumina in quantification as well, but most like in one of the further releases.
Using Illumina reads is a side feature and unfortunately is not the main focus of further developments at the moment.

Best
Andrey

**Comment by qingwangchen** [comment]
Dear @andrewprzh 

I have understood the situation and thanks for your patience in responding.

Thanks again🤗

Best
Qingwang

**Comment by andrewprzh** [comment]
Dear @qingwangchen 

No problem, I'll keep updated on the next release. So far you can use master branch, I hope it is quite stable.

Best
Andrey
