### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by shizhuoxing** [ablab/IsoQuant#133]
Hi,
I've been running isoquant-3.3.1-0 recently and encountered an "OSError: [Errno 24] Too many open files" error when processing the chromosome NW_019678884.1. I've attempted to rerun it three times using the "--resume" parameter, but the same error persists. Is there any way to resolve this issue?
![微信图片_20231223183858](https://github.com/ablab/IsoQuant/assets/17041305/6cc7f950-dae5-4b8a-b8c6-a8a302fec0ce)

**Comment by andrewprzh** [comment]
Dear @shizhuoxing 

I think it's an operating system limit, which can be changed using
```
ulimit -n <number>
```

I presume setting something like 10000 should be enough.

Best
Andrey

**Comment by biochristmas** [comment]
Hi,
I have recently encountered this problem as well. I set it to have no size limit using ‘ulimit -c unlimited,’ but I still receive errors.
![erro](https://github.com/ablab/IsoQuant/assets/107186260/947a749a-9a8c-43f0-8cfd-61c03cca8239)

**Comment by andrewprzh** [comment]
Dear @biochristmas 

The correct command is `ulimit -n`, while you mentioned you used `ulimit -c`. Could you try -n option and see if it helps?

Best
Andrey

**Comment by shizhuoxing** [comment]
I was able to run smoothly after setting the parameter 'ulimit -n 1000000', thanks!
