### ISSUE TITLE
Annotation problem

### ISSUE THREAD

**Issue by dawangran** [ablab/IsoQuant#135]
Hello, I have a question to consult, the number generated in the result is Ensembl ID, I want to specify the gene symbol, may I ask how to set it

**Comment by andrewprzh** [comment]
Dear @dawangran 

I'm not sure I got you question right. However, gene and transcript ids will always be re-used from the annotation. Gene name is also added to the resulting GTF. 
Currently, there are no options that would allow modifying the resulting GTFs. Probably, some utils like gffread may help you.

Best
Andrey

**Comment by andrewprzh** [comment]
New [IsoQuant 3.4](https://github.com/ablab/IsoQuant/releases/tag/v3.4.0) now copies information from the original reference annotation, including transcript and gene attributes. Hope that might help!
