### ISSUE TITLE
Alignment information

### ISSUE THREAD

**Issue by zpliu1126** [ablab/IsoQuant#139]
Hi~ Andrey,

> #43  This counts unique read-to-isoform assignments. Uniquely assigned read may not necessary be uniquely mapped, e.g. if its secondary alignment is mapped to intergenic region. Vise versa, ambiguous assignments may come from uniquely mapped reads, i.e. when the read covers only part of the gene and it is not clear which isoform it is (quite typical for truncated ONT reads). Thus, 40% for uniquely assigned reads seems to be ok.
To count uniquely mapped reads it's best to use original BAM file and samtools.

Is it possible to output the statistical information of minimap results in the log?

Best
zpliu

**Comment by andrewprzh** [comment]
Hi @zpliu1126

I will add it on my TODO list, this could be informative for the user. At the moment you can use, for example, samtools flagstat.
I'll keep you updated.

Best
Andrey

**Comment by andrewprzh** [comment]
Implemented in new [version 3.4](https://github.com/ablab/IsoQuant/releases/tag/v3.4.0)
