### ISSUE TITLE
question abount  data type of corrected Nanopore dRNA reads

### ISSUE THREAD

**Issue by baishengjun** [ablab/IsoQuant#142]
Hi,

I first use the transcriptclean to correct the nanopore dRNA reads generating the bam file. Should I set the data type parameter as transcript or Nanopore ? 

Thanks a lot,
Bai

**Comment by andrewprzh** [comment]
Dear @baishengjun 

I have never tried using transcriptclean myself. I am not entirely aware how it works, so I'd suggest running either with Nanopre or at PacBio data type. I also suggest to try running or raw data with Nanopore data type and see how it goes - IsoQuant has a lot of internal functions for read filtering and correction.

Best
Andrey

**Comment by baishengjun** [comment]
Dear @andrewprzh 

Thanks for your suggestion, I have tried it.
data type parameter set for nanopore and pacbio with transcriptclean bam file, and run with raw bam file generating the different result for discovered isoforms.
For transcriptclean bam file with data type parameter set for nanopore, it contains 2081 nic and 1392 nnic,
For transcriptclean bam file with data type parameter set for pacbio, it contains 3484 nic and 4374 nnic,
For raw bam file with  data type parameter set for nanopore,  it contains 2088 nic and 1412 nnic.
how to determine the suitable parameter for runing the pipeline. I think transcriptclean bam  and raw bam file both ok.
Any other mertics can be used to assess the result?

Thanks a lot,
Bai

**Comment by andrewprzh** [comment]
Dear @baishengjun 

I agree that both nanopore presets seem to be reasonable confirming the idea that IsoQuant performs ONT read correction by itself. Difference with PacBio preset can be explained by relaxed thresholds, relaxed read filtering and reporting mono-exonic transcripts in PacBio mode.

Estimating quality is not obvious when the ground truth is unknown. Here are some suggestions:

- Compare resulting GTFs using [gffcompare](https://ccb.jhu.edu/software/stringtie/gffcompare.shtml), see how well they correlate. If you are looking for the most reliable ones,  Take a look at "unique" transcripts (i.e. reported only by a single method), see how well they are supported by the alignments in IGV or othe genome browser;
- Run the same methods on [SIRV](https://www.lexogen.com/sirvs/) sequencing data. Existing SIRV datasets are published in I[soQuant paper](https://www.nature.com/articles/s41587-022-01565-y) ([link to Zenodo](https://zenodo.org/records/7611877)) and [LRGASP benchmark](https://www.biorxiv.org/content/10.1101/2023.07.25.550582v1). I suggest using incomplete annotation, or even no annotation to test how well novel transcripts are discovered by different pipelines, you can use gffcompare to compare against the ground truth (same as I did in IsoQuant paper).
- Use simulated data (e.g. from IsoQuant paper), however, keep in mind that simulated data still has some biases compared to real sequencing. 

Best
Andrey
