### ISSUE TITLE
BUG：Number of labels is not equal to the number of samples

### ISSUE THREAD

**Issue by dawangran** [ablab/IsoQuant#145]
Hello, I have been running three samples, but I keep reporting errors, the number of samples is different, may I ask how to solve it?

${python_cyclone} ${isoquant}  --data_type nanopore --bam ${outdir}/ZF_1-2/01.data/ZF_1-2_sorted.bam ${outdir}/ZF_128-1/01.data/ZF_128-1_sorted.bam ${outdir}/ZF_128-2/01.data/ZF_128-2_sorted.bam --complete_genedb --genedb ${gtf} --reference ${ref} --output ${outdir}/01.isoquant  --count_exons --check_canonical --force --labels A1 A2 A3

**Comment by andrewprzh** [comment]
Dear @dawangran 

Could you send me the isoquant.log file, please?

Best
Andrey

**Comment by andrewprzh** [comment]
Please, reopen if you still encounter this issue in new [IsoQuant 3.4](https://github.com/ablab/IsoQuant/releases/tag/v3.4.0)
