### ISSUE TITLE
Executing IsoQuant in CWL environment ends in failure

### ISSUE THREAD

**Issue by sagnikbanerjee15** [ablab/IsoQuant#149]
Hello,

I am using IsoQuant within a docker environment and executing it via cwltool. The execution finishes but then fails when IsoQuant tries to link the genome file in the output directory. cwltool executes everything in a docker container. So, when IsoQuant tries to create a link to the reference file (which is present in the container) in the output folder, an error is generated since the container is now removed. Is there any particular reason to have that link in the output folder? Is there a way to disable it?

Thank you,
Sagnik

**Comment by sagnikbanerjee15** [comment]
Hello,

I fixed the issue, there was a problem in my CWL script.

Thanks

**Comment by andrewprzh** [comment]
Hi @sagnikbanerjee15 

Good, hope everything runs smooth on your side!

Best
Andrey
