### ISSUE TITLE
Prevent IsoQuant from creating any new genes

### ISSUE THREAD

**Issue by sagnikbanerjee15** [ablab/IsoQuant#150]
Hello,

Is it possible for IsoQuant to quantify genes and isoforms present only in the reference gtf file, and not generate any new gene and/or isoform? Would the `--no_model_construction` achieve this?

Thank you

**Comment by andrewprzh** [comment]
Dear @sagnikbanerjee15 

You are absolutely right, with `--no_model_construction` IsoQuant will only perfrom read-to-isoforms assignment and reference gene/isoform quantification. Novel transcript discovery will not be launched.

Best
Andrey
