### ISSUE TITLE
geneDB question

### ISSUE THREAD

**Issue by dawangran** [ablab/IsoQuant#152]
Hello, I have a question I don't understand. I have four samples from the first batch and have run the program. A genedb is generated, can I use this genedb directly for the second batch of samples? You need to ensure that new transcripts are named consistently.
Or is there any other way to ensure that the new transcripts of the two batches of samples are named the same.

**Comment by andrewprzh** [comment]
Dear @andrewprzh 

If you mean the reference gene DB, yes, it can be reused for the second run and reference names will be the same.

If you mean the resulting annotation with novel transcripts, there will be no consistency between 2 individual runs. 
You want to provide all 8 samples to the same run. You will get a single GTF as an output, as well per-sample transcript count table.

Hope this clarified the matter. 

Best
Andrey

**Comment by dawangran** [comment]
Hello, can I guarantee the consistency of the new transcript as long as I use the same geneDB? Although he is different to run.

**Comment by andrewprzh** [comment]
No, there will be no consistency in novel isoform naming in different runs. Even identical novel transcripts will have completely different names.

Best
Andrey

**Comment by dawangran** [comment]
Hello, how can I maintain consistency in naming new transcripts? For my different batches of samples.

**Comment by andrewprzh** [comment]
As I mentioned previously, the best way would be to run all the samples at once and then use count tables to understand which isoforms express in which samples.

Best
Andrey
