### ISSUE TITLE
feature request: an option for compressing the output files

### ISSUE THREAD

**Issue by jamestwebber** [ablab/IsoQuant#154]
IsoQuant produces some large text files as part of its output, in particularly `read_assignments.tsv`. These files are quite verbose and so they are ripe for compression. As a test, I gzipped all the `tsv`, `bed` and `gtf` files from a run, and the output directory went from 18G to 1.7G, so about 10% of the size. So this saves a lot of space, and could even save time when disk IO is an issue.

There are better compression options than `gzip`, but it's widely available and easily read/written via Python.

**Comment by andrewprzh** [comment]
I agree, making a gzipped output doen't seem to be like a complex thing to implement.

Moreover, I thought of making an option for specifying which output files are needed. I'll try to do it before the next release.

**Comment by andrewprzh** [comment]
Large files are now compressed by default in [IsoQuant 3.4](https://github.com/ablab/IsoQuant/releases/tag/v3.4.0)
`--no_gzip` option enables previous behavior.
