### ISSUE TITLE
Sequence fasta file corresponding to the final output GTF file

### ISSUE THREAD

**Issue by seongwoohan** [ablab/IsoQuant#157]
Hi,

I am aware SAMPLE_ID.transcript_models.gtf is an updated GTF annotation for detected isoforms, but is there an actual sequence in a fasta file corresponding to that gtf file? Is there a way to get that file as part of the final output?

Thank you!

**Comment by andrewprzh** [comment]
@seongwoohan 

For extracting transcript sequences using the resulting GTF I suggest using [gffread](http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread):
```
gffread -w <output_transcripts.fasta> -g <genome.fasta>  <SAMPLE_ID.transcript_models.gtf>
```

Best
Andrey
