### ISSUE TITLE
IsoQuant does not produce any counts when model construction is turned off

### ISSUE THREAD

**Issue by sagnikbanerjee15** [ablab/IsoQuant#161]
Hello,

I am using the following command to generate counts. The reads have been aligned to the genome and a transcriptome gtf file has been provided to the program. 

```
python /opt/conda/bin/isoquant.py --reference genome.fasta  --sqanti_output  --bam  SGNex_H9_directRNA_replicate1_0.01_aligned.sortedByPos.bam SGNex_H9_directRNA_replicate2_0.01_aligned.sortedByPos.bam SGNex_H9_directRNA_replicate3_0.01_aligned.sortedByPos.bam SGNex_HEYA8_directRNA_replicate1_0.01_aligned.sortedByPos.bam SGNex_HEYA8_directRNA_replicate2_0.01_aligned.sortedByPos.bam SGNex_HEYA8_directRNA_replicate3_0.01_aligned.sortedByPos.bam  -o isoquant_output_dir  --complete_genedb  --model_construction_strategy default_ont  --report_novel_unspliced true  --gene_quantification unique_only --transcript_quantification unique_only  --splice_correction_strategy default_ont --genedb /var/lib/cwl/stg405bb1bb-0ea4-431c-873b-317e94a42809/stringtie_merged.gtf --data_type nanopore --no_model_construction --threads 48
```

The execution completes without an error but produces empty count files. Interestingly, when I execute the same command without "no_model_construction" it generates counts evident from "OUT.transcript_model_grouped_counts.tsv". Is there any modification required to the command?

Also, isoquant produces a lot of count files and it could sometimes be difficult to understand which one to use. I require transcript counts only.

Thank you.

**Comment by andrewprzh** [comment]
@sagnikbanerjee15 

If you are interested in reference transcript counts, you need `.transcript_counts.tsv`, not `transcript_model_counts.tsv`.
The former ones corresponds to discovered transcript models.

The output files are also described here https://github.com/ablab/IsoQuant?tab=readme-ov-file#sec3.3

Best
Andrey

**Comment by sagnikbanerjee15** [comment]
Thanks. I will rerun it. Also, is it possible to turn off gene and transcript quantification?

**Comment by andrewprzh** [comment]
> Also, is it possible to turn off gene and transcript quantification?

No. 

> I just completed the execution and I checked all the counts files. All of those are empty.
Could you send me the isoquant.log file?

**Comment by sagnikbanerjee15** [comment]
Here is the file
[Uploading isoquant.log…]()

**Comment by andrewprzh** [comment]
@sagnikbanerjee15 

The log reads

```
2024-03-05 11:53:25,053 - INFO - Read assignment statistics
2024-03-05 11:53:25,053 - INFO - intergenic: 83038
```

Which means not a single read was mapped to a gene. Thus it looks like a problem with the input data.

This may have different reasons
- You GTF or BAM files have different chromosome names than your reference FASTA;
- You specified `--complete_genedb` option (which is recommended only for official annotations), but you annotation does not contain gene and transcript features.

Best
Andrey

**Comment by sagnikbanerjee15** [comment]
Thank you. This fix has worked. Does Isoquant not report transcripts that has a value of zero for all samples?

**Comment by andrewprzh** [comment]
In the new [IsoQuant 3.4](https://github.com/ablab/IsoQuant/releases/tag/v3.4.0) all reference transcript should be reported regardless of their abundance value.
