### ISSUE TITLE
Novel gene with overlapping coordinates by using reference annotation

### ISSUE THREAD

**Issue by zpliu1126** [ablab/IsoQuant#164]
Hi~ Andrey,

After updating the GFF annotation with Isoquant, I found many Novelgenes with overlapping coordinates when I used Stringtie to calculate the gene expression downstream. I guess these may be different transcripts of the same gene, and they are not well combined.

```bash
#* example of novel gene
cat  A2.extended_annotation.gtf|grep 108761523|awk '$3=="gene"{print $0}'

###########restul##############
Chr12	IsoQuant	gene	108761523	108762488	.	+	.	gene_id "novel_gene_Chr12_177202"; transcripts "1"; 
Chr12	IsoQuant	gene	108761523	108765123	.	+	.	gene_id "novel_gene_Chr12_177104"; transcripts "1"; 
Chr12	IsoQuant	gene	108761523	108765123	.	+	.	gene_id "novel_gene_Chr12_177106"; transcripts "1"; 
Chr12	IsoQuant	gene	108761523	108765123	.	+	.	gene_id "novel_gene_Chr12_177152"; transcripts "1"; 
Chr12	IsoQuant	gene	108761523	108765123	.	+	.	gene_id "novel_gene_Chr12_177154"; transcripts "1";
```
Best
zpliu

**Comment by andrewprzh** [comment]
Dear @zpliu1126 

Current gene detection algorithm is based purely on spliced sites shared between transcripts. Probably, using exonic overlaps also makes sense.
Could you send all GTF lines for these genes?

Best
Andrey

**Comment by zpliu1126** [comment]
> Dear @zpliu1126
> 
> Current gene detection algorithm is based purely on spliced sites shared between transcripts. Probably, using exonic overlaps also makes sense. Could you send all GTF lines for these genes?
> 
> Best Andrey

I haven used gffread to merge those transcripts.
```bash
 gffread  -M  --cluster-only isoquant.gff >isoquant_collapse.gff
```
Best
zpliu

**Comment by andrewprzh** [comment]
@zpliu1126 

Thanks for the data, at looks that at least some transcripts share splice sites. I'll try to improve the algorithm for detecting same-gene transcripts.

Best
Andrey

**Comment by andrewprzh** [comment]
Novel gene merging strategy is completely reworked in [IsoQuant 3.4](https://github.com/ablab/IsoQuant/releases/tag/v3.4.0), should be fixed now.
