### ISSUE TITLE
IsoQuant with yaml input

### ISSUE THREAD

**Issue by lebronzhong** [ablab/IsoQuant#166]
Hi~ Andrey,
    I encountered trouble using the -- yaml parameter of IsoQuant. I want to use yaml to input file, but an error message told me that this parameter is not available. I installed it using Conda, can you help me solve it?

`usage: isoquant.py [-h] [--output OUTPUT] [--debug] [--genedb GENEDB]
                   [--complete_genedb] [--reference REFERENCE] [--index INDEX]
                   [--clean_start] [--bam BAM [BAM ...] | --fastq FASTQ
                   [FASTQ ...] | --bam_list BAM_LIST | --fastq_list
                   FASTQ_LIST] [--prefix PREFIX]
                   [--labels LABELS [LABELS ...]] [--read_group READ_GROUP]
                   [--data_type {pacbio_ccs,pacbio,nanopore,ont,assembly,transcripts}]
                   [--stranded STRANDED] [--fl_data]
                   [--matching_strategy {exact,precise,default,loose}]
                   [--splice_correction_strategy {none,default_pacbio,default_ont,conservative_ont,all,assembly}]
                   [--model_construction_strategy {reliable,default_pacbio,sensitive_pacbio,fl_pacbio,default_ont,sensitive_ont,all,assembly}]
                   [--transcript_quantification {unique_only,with_ambiguous,with_inconsistent,all}]
                   [--gene_quantification {unique_only,with_ambiguous,with_inconsistent,all}]
                   [--report_novel_unspliced REPORT_NOVEL_UNSPLICED]
                   [--full_help] [--test] [--threads THREADS]
                   [--check_canonical] [--sqanti_output] [--count_exons]
                   [--resume | --force] [--no_model_construction]
                   [--run_aligner_only] [--version]
isoquant.py: error: unrecognized arguments: --yaml dataset_1.yaml
yhrun: error: cn7465: task 0: Exited with exit code 2
`
Best,
lebronzhong

**Comment by andrewprzh** [comment]
@lebronzhong 

Yes, the genes with 0 counts are not printed. So the only way is to merge them via some python/R script, I guess.
I will fix this issue in the next release.

Best
Andrey

**Comment by andrewprzh** [comment]
Finally, IsoQuant 3.4 is released with YAML support. Also, reference and transcript genes with 0 counts are now always printed.
