### ISSUE TITLE
Question about Canonical

### ISSUE THREAD

**Issue by dongdongdong0203** [ablab/IsoQuant#171]
Hi developers,

I added the `--check_canonical` parameter when using isoquant. 
Some of the transcript attributes in the GTF file appear `Canonical "False"`. 

Can these transcripts be considered unreliable. Do they need to be removed in downstream analyses or can they be retained?

Thanks

**Comment by andrewprzh** [comment]
Dear @dongdongdong0203 

I think it's up to you and your analysis goals whether to include those or not. In general they might have lower level of reliability, but on the other hand - they must have at least some read support to be reported.
In the next version IsoQuant will report only canonical transcripts by default. 

Best
Andrey

**Comment by dongdongdong0203** [comment]
Dear @andrewprzh 

Thank you for your prompt reply.

 If I want to remove transcripts of `canonical fales` at the moment, what method do you recommend? 

Also, can you please tell me when the next version will be updated, I'm really looking forward to features like `--report_unstranded` etc.

Best
RUAN

**Comment by dongdongdong0203** [comment]
Dear @andrewprzh 

I had a similar problem (#140).

I used the `AGAT` tool to compare the reference GTF with the `extended_annotation.gtf` and found that the reference gene was missing. Very much looking forward to a new version that will fix it.

Best
RUAN

**Comment by andrewprzh** [comment]
Dear @dongdongdong0203 

>If I want to remove transcripts of canonical false at the moment, what method do you recommend?
Not sure I know a tool for that, maybe gffread has options?

Hopefully I'll be able to pull all these new features and fixes together within a week or two and finally make a new release.
I've been delaying it for too long due to other ongoing projects...

Best
Andrey

**Comment by andrewprzh** [comment]
Dear @dongdongdong0203 

If understood correctly, you would like to have an option for remove non-canonical transcripts from the resulting annotation, right?
This feature is already implemented and will be released in the version 3.4, hopefully soon!

Best
Andrey

**Comment by dongdongdong0203** [comment]
Dear @andrewprzh 

I just wanted to clarify that there might be a slight misunderstanding. 

What I meant was that only certain reference transcripts are considered non-canonical, and I would like to remove only the non-canonical discovery transcripts. 

Hope that clears things up!

```
1	IsoQuant	transcript	96218	186716	.	-	.	gene_id "ENSSSCG00000029697"; transcript_id "ENSSSCT00000055371"; exons "10"; Canonical "False";
1	IsoQuant	transcript	121147	175734	.	-	.	gene_id "ENSSSCG00000029697"; transcript_id "ENSSSCT00000093585"; exons "12"; Canonical "False";
1	IsoQuant	transcript	121406	186769	.	-	.	gene_id "ENSSSCG00000029697"; transcript_id "ENSSSCT00000038814"; exons "10"; Canonical "False";
1	IsoQuant	transcript	121406	186769	.	-	.	gene_id "ENSSSCG00000029697"; transcript_id "ENSSSCT00000047788"; exons "9"; Canonical "False";
1	IsoQuant	transcript	170565	186716	.	-	.	gene_id "ENSSSCG00000029697"; transcript_id "ENSSSCT00000063290"; exons "4"; Canonical "False";
```

Best
RUAN

**Comment by dongdongdong0203** [comment]
Dear @andrewprzh 

Thank you so much for your patience! We can't wait to release the new version very soon!

Best
RUAN
