### ISSUE TITLE
Transcript quantification

### ISSUE THREAD

**Issue by dawangran** [ablab/IsoQuant#174]
Hello，
I have a few questions I'd like to consult.
*transcript_grouped_counts.tsv   is the result of unique reads.
*transcript_model_grouped_counts.tsv    is the result of  inconsistent reads.
The reads for the two files are different.

If I need to consider new transcript quantification and known transcript quantification should I add the two files together？
If my understanding above is correct, why would transcript_model_grouped_counts.tsv include quantitative results of known transcripts?

Looking forward to your reply！

By Dawn

**Comment by andrewprzh** [comment]
Dear @dawangran 

Not exactly.

`*transcript_grouped_counts.tsv` contains count values for reference transcripts only. It is done before novel transcript discovery and is produced for those who are interested only in reference gene/transcript expression.

`*transcript_model_grouped_counts.tsv` contains counts for both novel and known transcripts. I guess this is the file you need. No need to combine tables.

In theory, the first file is a subset of a second file. However, as the methodology slightly differs, counts are different. In the next release they will be more similar. I hope to release version 3.4 within couple weeks.

Best
Andrey

**Comment by dawangran** [comment]
Dear professor,

I hope this email finds you well. I am writing to seek clarification and address some concerns I have encountered while using IsoQuant for single-cell long-read transcript quantification analysis.

Firstly, I utilized the default parameters for constructing the transcript model, which resulted in the generation of the "transcript_model_grouped_counts.tsv" file. Subsequently, we calculated the average expression level per cell and the number of detected genes based on this file. However, we observed instances where the expression count(UMI) was lower than the number of genes , which struck me as quite perplexing. I would greatly appreciate your insights into the potential reasons underlying this phenomenon.

Furthermore, I have read the original paper and found myself somewhat confused regarding the treatment of "inconsistent reads." Specifically, I would like to understand whether inconsistent reads are included in the transcript quantification process and, if so, whether their counting weight aligns with the principles applied to ambiguous reads. If inconsistent reads are not considered for transcript quantification, I am curious to know how they are handled. The statistical report generated from my data indicates the presence of inconsistent reads, which prompted this inquiry.

Thank you in advance for your assistance and prompt response. I am eagerly looking forward to your insights on these matters.

Sincerely

**Comment by andrewprzh** [comment]
Dear @dawangran 

>However, we observed instances where the expression count(UMI) was lower than the number of genes , which struck me as quite perplexing. I would greatly appreciate your insights into the potential reasons underlying this phenomenon.

Could you give me an example? I am not sure I entirely got the issue you observe.

By default, inconsistent reads are not used for quantification. So, inconsistent reads are simply ignored, since IsoQuant was not able to assign them to any known transcript.
However, IsoQuant has `--gene_quantification` and `--transcript_quantification` options, with which you can control how different categories are treated.

Do not hesitate to ask further questions.

Best
Andrey

**Comment by andrewprzh** [comment]
Just in case, new IsoQuant 3.4 was just released. Quantification was significantly improved in this vesion.
