### ISSUE TITLE
Keep CDS feature in final results

### ISSUE THREAD

**Issue by xiekunwhy** [ablab/IsoQuant#176]
Hi,

Is it possible to keep the reference CDS feature in final gtf (OUT.extended_annotation.gtf), if not, would you please make it possible?

Best,
Kun

**Comment by andrewprzh** [comment]
Dear @xiekunwhy 

Currently, there is no such option, but I'll check if it can done for the next release.

Best
Andrey

**Comment by andrewprzh** [comment]
CDS and other features, as well as gene and transcript attributes are now copied from the reference annotation in the new [IsoQuant 3.4](https://github.com/ablab/IsoQuant/releases/tag/v3.4.0)
