### ISSUE TITLE
About quantifying to use my own gtf

### ISSUE THREAD

**Issue by hyeon9** [ablab/IsoQuant#184]
Hi, Thank you for developing a useful tool!

Currently, I'm using my own gtf file (generated from long read data), and it takes a little bit of time to create db file using gffutils even though I applied the "--no_model_construction" option.

So,my question is that If I want to generate a count matrix based on my gtf file, would it be okay to use the manually generated genedb file with the options "disable_infer_transcripts=False, disable_infer_genes=False"?
I just want to reduce the running time.

Thank you,
Hyeon9

**Comment by andrewprzh** [comment]
Dear @hyeon9 

Thanks for the feedback!

It depends on how you GTF looks. If it has all `gene` and `transcript` features, you can safely use `--complete_genedb` option, which runs gffutils with `"disable_infer_transcripts=False, disable_infer_genes=False`.

However, if you only `exon` features, creating a proper gffutils DB is necessary, including counting transcripts (`--no_model_construction` disables only novel transcript discovery). The good thing you need to do conversion only once.

If you are unsure, you can paste a few lines from your GTF here.

Best
Andrey

**Comment by hyeon9** [comment]
Appreciate your quick response!

My gtf has only transcript and exon in 3rd column (I've attached a few lines of my GTF), if so would it be okay using this **gffutils.create_db(gtf, db, force=True, keep_order=True, merge_strategy='error', sort_attribute_values=True, disable_infer_transcripts=False, disable_infer_genes=True)** ?
chr1    FLAIR   transcript      14404   16288   .       -       .       gene_id "chr1:14000"; transcript_id "d3813efc-9843-4ee3-979a-8c5886747a0b";
chr1    FLAIR   exon    14404   16288   .       -       .       gene_id "chr1:14000"; transcript_id "d3813efc-9843-4ee3-979a-8c5886747a0b"; exon_number "0";
chr1    FLAIR   transcript      27544   28851   .       -       .       gene_id "chr1:27000"; transcript_id "f261b4fe-b3aa-40c8-943e-51a68c20ea84";
chr1    FLAIR   exon    27544   28851   .       -       .       gene_id "chr1:27000"; transcript_id "f261b4fe-b3aa-40c8-943e-51a68c20ea84"; exon_number "0";
chr1    FLAIR   transcript      28589   29341   .       -       .       gene_id "chr1:28000"; transcript_id "9d3bb6a5-cc25-4215-a5d8-a91f6541eb57";
chr1    FLAIR   exon    28589   29341   .       -       .       gene_id "chr1:28000"; transcript_id "9d3bb6a5-cc25-4215-a5d8-a91f6541eb57"; exon_number "0";
chr1    FLAIR   transcript      99093   100210  .       -       .       gene_id "chr1:99000"; transcript_id "bcd3b41c-472a-4625-8d5c-e45bbbb1a32d";
chr1    FLAIR   exon    99093   100210  .       -       .       gene_id "chr1:99000"; transcript_id "bcd3b41c-472a-4625-8d5c-e45bbbb1a32d"; exon_number "0";


Thank you,
Hyeon9

**Comment by andrewprzh** [comment]
@hyeon9 

I think you need to use `disable_infer_genes=False` as well. IsoQuant needs both transcript and gene features to run correctly.
You can use IsoQuant's script `src/gtf2db.py` which runs exactly the same function with correct flags.

Best
Andrey

**Comment by hyeon9** [comment]
Oh so sorry, I made a mistake.
I should use this one, because my GTF have exon and transcript.
`gffutils.create_db(gtf, db, force=True, keep_order=True, merge_strategy='error', sort_attribute_values=True, disable_infer_transcripts=True, disable_infer_genes=False)`

sorry for bothering you.

**Comment by andrewprzh** [comment]
Oh, sure, if exons are there, then you only need to infer genes.

Best
Andrey

**Comment by hyeon9** [comment]
Thank you so much !!

Hyeon9

**Comment by andrewprzh** [comment]
I'll close this issue now, re-open if needed.
