### ISSUE TITLE
Strandedness for pacbio?

### ISSUE THREAD

**Issue by astarr97** [ablab/IsoQuant#185]
Hello, thanks for developing this tool, it has been really useful and much easier to get up and running than the other tools we tried!  

I had a quick somewhat naive question about running isoquant on pacbio IsoSeq from the new Kinnex platform.  In the input fastq, all transcripts are oriented 5'->3' which is (at least I think) how the file encodes the strandedness of the data.  My question is: does isoquant automatically take this into account using the defaults for pacbio?  Or is there some way to specify this when running?  Alternatively, does IsoSeq not encode the strandedness of the original RNA molecule?  

Thanks again for developing and maintaining this program!

**Comment by astarr97** [comment]
Hi Andrey,

Thanks for the quick reply!  I am passing in reads with polyA tails.  In that case, does IsoQuant figure out the stranding from that + canonical splice sites so that it knows whether to assign a read to a gene or its antisense transcript?  Just want to make sure I don't need to pass any additional information for IsoQuant to be able to distinguish which strand to assign reads to.  Thanks!

Best, Alex.

**Comment by andrewprzh** [comment]
Dear Alex

Yes, reads with polyA tails should be enough. 

Reads are assigned based on their alignment coordinates. If a read matches a transcript but polyA or canonical sites indicate an opposite strand, it is marked as anitsense.
However, if a read does not match a known transcript (i.e. contradicts all known transcripts), it will likely flagged as `inconsistent` independently of the strand.

Best
Andrey
Best
Andrey

**Comment by astarr97** [comment]
Perfect, thank you!
