### ISSUE TITLE
Error message about concurrent futures process

### ISSUE THREAD

**Issue by P10911004-NPUST** [ablab/IsoQuant#186]
Hi Andrey,

I encountered with the concurrent error.

[isoquant.log](https://github.com/ablab/IsoQuant/files/15260457/isoquant.log)

By the way, are there any options for directly combining the chromosome-wise outputs into one output?

![image](https://github.com/ablab/IsoQuant/assets/73229125/8e8e1137-1769-42d2-9ca2-992ab153b1bd)

Thank you very much!

**Comment by andrewprzh** [comment]
@P10911004-NPUST 

Thanks for the report! There is bug in the new version that only affects `--sqanti_output` option. So you can re-run IsoQuant without this option.
We will make a new bug-fix release soon.

Chromosome-wise outputs will be automatically merged if the run is successful. When the fixed version is out, you can resume your previous run with `isoquant.py --resume -o <you previous output folder`. 

Best
Andrey

**Comment by andrewprzh** [comment]
Should be fixed in https://github.com/ablab/IsoQuant/releases/tag/v3.4.1

**Comment by P10911004-NPUST** [comment]
It works well now. Thank you!
