### ISSUE TITLE
Combining multiple data from different methods (direct RNA, pacbio ISOSEQ... etc)

### ISSUE THREAD

**Issue by jjuhyunkim** [ablab/IsoQuant#193]
Hi developers,

I have nanopore direct RNA, cDNA of RNA, and PacBio ISOSEQ and MAS-seq data from one sample, but from three different cell lines. Could you advise me on the best approach to analyze them together?

Should I run them separately based on the library preparation methods and then merge the output GTF files into one using the gffread tool?
* ISOQUANT run # 1 : ONT direct RNA from cell line # 1, # 2 and # 3 
* ISOQUANT run # 2 : ONT cDNA of RNA from cell line # 1, # 2 and # 3
* ISOQUANT run # 1 :  Pacbio ISOSEQ from cell line # 1, # 2 and # 3

Thanks!

**Comment by andrewprzh** [comment]
Hi @jjuhyunkim 

I have never performed this kind of experiments, so I'd try to different runs and see which gives more reliable results:
1. As you proposed, run everything separately with appropriate data types and then merge the resulting annotations. Quantification can be done bu running IsoQuant again using merged annotation and the same BAM files.
2. Provide all files together in a single run setting nanopore data type.

Taking into account the coverage difference, my bet is on the first approach.

Best
Andrey

**Comment by andrewprzh** [comment]
Please, reopen if you have further questions.
