### ISSUE TITLE
if isoquant perfomed the isoform collapse?

### ISSUE THREAD

**Issue by wjcre2023** [ablab/IsoQuant#199]
Hi

Thank you for this amazing software! It's so helpful for me.
I used pychopper software and generated the FL.fq files as the input for isoquant(3.4.1) program. Whether should I perform the isoform collapse additionally after mapping by minimap2? Such as perform collapse_isoforms_by_sam.py program. Is isoform collapse included in the isoquant pipline? 

In addition, I tried to filter isoforms by --min_mapq 10 argument. But I got the same size bam files and similar isoform numbers with or without this argument. It makes me confused.

Best
Jie
![image](https://github.com/ablab/IsoQuant/assets/150228007/a3a32688-1482-4f81-a034-478912d28822)

**Comment by andrewprzh** [comment]
Dear @wjcre2023 

Thanks for the feedback!

IsoQuant does not need any preprocessing, especially collapsing isoforms. I have not tried pychopper, it may have a positive effect, but IsoQuant also like polyA tails in the reads, so make sure those are not trimmed.

MAPQ 10 seems like a quite low cutoff, which, indeed, may have a very little effect on the isoform construction. However, I am not sure larger cutoff is needed.
BAM file will be the same, as MAPQ filtering is done later in IsoQuant and does not affect minimap alignment.

Best
Andrey

**Comment by Tang-pro** [comment]
Hi @andrewprzh 

IsoQuant doesn't require collapse, so I'm curious, how does it anchor reads to transcript positions and calculate expression?
Thanks!

**Comment by andrewprzh** [comment]
@Tang-pro 

When computing expression for reference isoforms, IsoQuant assigns them base on splice site coordinates of reference transcripts and aligned reads.

During the isoform discovery step reads are used to construct a so-called intron graph, which is further used to derive isofroms as paths in the graph. 

Both algorithms are described in the [methods sections ](https://www.nature.com/articles/s41587-022-01565-y#Sec2) of our publication.

Best
Andrey
