### ISSUE TITLE
 Choosing the ‘--data_type’ parameter for combined PacBio CCS and Nanopore data

### ISSUE THREAD

**Issue by biochristmas** [ablab/IsoQuant#208]
Hi
I have two sets of input data, one from Nanopore and the other from PacBio. Could you please advise on the ‘--data_type’ parameter? Should I choose ‘pacbio_ccs’ or ‘nanopore’? My goal is to obtain an annotated file after annotation extension.

**Comment by andrewprzh** [comment]
Hi @biochristmas 

If you want to do in in a single IsoQuant run, I'd suggest to use nanopore as a datatype.
However, if PacBio has a noticeably lower coverage, PacBio reads may be ignored in some cases.

Alternatively, you run IsoQuant twice and merge the resulting annotations using, for example, gffcompare.

Best
Andrey

**Comment by biochristmas** [comment]
Hi @andrewprzh 
I performed Isoquant twice, once with Nanopore data and once with PacBio data. Now I have two annotation files, and I tried using gffcompare to merge them, but it doesn’t seem quite right; it appears to deduplicate individual annotation files. For the software gffcompare, which is used to merge and deduplicate the results of Isoquant from two annotation files, do you have recommended commands for merging and deduplicating?
![1](https://github.com/ablab/IsoQuant/assets/107186260/b416d971-2a34-4fb3-ad3c-92b452420f96)
![2](https://github.com/ablab/IsoQuant/assets/107186260/f9c01401-5a36-4e6d-9ed4-c9a7a6e8a98b)

**Comment by andrewprzh** [comment]
@biochristmas 

I think the merger GTF should be in `gffcompare/merge.combined.gtf`, could you double check if you have this file in your output?

**Comment by biochristmas** [comment]
Hi  @andrewprzh
I executed this command: gffcompare -r reference.gtf -R -G -o merge -i list.txt (the list.txt file contains the GTF files from Isoquant annotation expansion for Nanopore and PacBio data). I have obtained the merge.combined.gtf file, but I am not sure if merge.combined.gtf contains redundant transcripts

**Comment by biochristmas** [comment]
@andrewprzh 
Thank you for your prompt response. The issue has been resolved. Best regards and good luck!

**Comment by andrewprzh** [comment]
@biochristmas 

> I have obtained the merge.combined.gtf file, but I am not sure if merge.combined.gtf contains redundant transcripts

I would assume it does not contain redundant transcritps, at least that seems reasonable from my point of view. However, it's better to double check or ask gffcompare developers.

Best
Andrey

**Comment by andrewprzh** [comment]
I'll close this issue for now, please, re-open if needed.
