### ISSUE TITLE
Again : Cannot recognize the spectrum ID Spectrum :)

### ISSUE THREAD

**Issue by cleopatraface** [ablab/IsoQuant#21]
Hi, 
I am sorry I am posted the same issue twice, but I think I understand the problem better and may need some help to fix it.

I receive this message when I use IonQuant.
It creates the quant.csv files ( even quantbin) but it can't update the protein.tsv 
In my code, I run IonQuant in the working directory where all integrated the report files are present. ( for PSM , I concatenated all the PSM from the subdirectories in one file in the working directory.)
with every sample it gives me.

2021-08-24 15:33:40 [INFO] - Quantifying...
2021-08-24 15:33:40 [INFO] - Updating Philosopher's tables...
java.lang.Exception: Cannot recognize the spectrum ID Spectrum
	at z.a(Unknown Source)
	at q.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)

I was checking where else is spectrum ID is recorded except in psm.tsv, I couldn't find. I think if I knew where else spectrum ID is used ,I can understand better and fix the problem.

Also, very important question for me,  for --mbr, should I use the working directory ( where all integrated and quant files are present)  for --specdir  flag , or  should I use multiple --specdir ( my 15 samples) ?
Thanks in advance for your help. 
Still challenging my self :)

**Comment by andrewprzh** [comment]
Hi, this is github of IsoQuant, not IonQuant (nothing in common), please address this issue to their support :)
