### ISSUE TITLE
How does isoquant assign isoforms in nanopore run where 5'ends are degraded?

### ISSUE THREAD

**Issue by obegik** [ablab/IsoQuant#22]
Hi,

Could you please clarify how the reads are assigned when there is more than one isoform that would match the read (i.e. because 5' ends have not yet been sequenced for that read, making the assignment difficult). 

Also, it is a bit unclear from the GitHub documentation how the read-to-isoform algorithm decides which isoform is the one that a given read corresponds to. 

Thanks,
Oguzhan Begik

**Comment by andrewprzh** [comment]
Dear Oguzhan Begik

Thank you for your question! We are currently working on the manuscript, which we hope will be available soon.

In brief, IsoQuant mainly relies read's intron chain and matches it against intron chains of known isoforms (in fact, exon coverage is also used but only as a supplementary information):
- If read's intron chain matches to a single known isoform, it is reported as unique. Even if 5' is degraded, read may still contain enough information to unambiguously decide which isoform it is;
- If it's degraded so much that multiple isoforms match, read is reported as ambiguous;
- If intron chain matches to none of the isoforms from the annotation it is reported as inconsistent (potentially novel isoform or misalignment).

Let me know if you'd like to know more details.

Best
Andrey

**Comment by obegik** [comment]
Dear Andrey,

Thanks for your prompt response. They have been very helpful.

Best,
Oguzhan

**Comment by andrewprzh** [comment]
Hi, the preprint is now available at https://www.researchsquare.com/article/rs-1571850/v1

Best
Andrey
