### ISSUE TITLE
Feature request: add command line option to specify desired output type

### ISSUE THREAD

**Issue by ljwharbers** [ablab/IsoQuant#223]
Hi,

I was wondering if you were thinking of implementing a simple tag, `--linear` and/or `--matrix` for instance, to let the user specify the desired output. The matrix format is definitely the more time and storage-hungry step compared to the two so it would be nice to be able to forego depending on use-case.

Thanks,
Luuk

**Comment by andrewprzh** [comment]
Dear @ljwharbers 

Sure, will add it to the next release.

Best
Andrey

**Comment by andrewprzh** [comment]
`--counts_format` option is now available in version 3.5.1.

**Comment by ljwharbers** [comment]
Thanks for letting me know Andrew and good to hear that it is now fixed! I'll make sure to rerun some of my previous analysis.
