### ISSUE TITLE
Samtools sort error resolved with v1.14

### ISSUE THREAD

**Issue by danledinh** [ablab/IsoQuant#24]
Got this error:
```
samtools sort: truncated file. Aborting
*** Error in `samtools': free(): invalid size: 0x00007ffb68250010 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81679)[0x7ffff7570679]
/gstore/home/led13/.conda/envs/liqa/bin/../lib/libhts.so.3(+0x47786)[0x7ffff7f7e786]
/gstore/home/led13/.conda/envs/liqa/bin/../lib/libhts.so.3(hts_close+0xb6)[0x7ffff7f6b246]
samtools(+0x25595)[0x555555579595]
samtools(+0x266b4)[0x55555557a6b4]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7ffff7511505]
samtools(+0xa109)[0x55555555e109]
```
Used samtools v1.14 in different conda env to successfully sort xxx.sam intermediate file in `aux` directory. The resultant xxx.bam file was used as input to the pipeline (using --bam flag) with no other errors.

Perhaps, you can update your conda requirements to include an updated samtools version?

**Comment by andrewprzh** [comment]
Thanks a lot for the suggestions! I've updated the dependency versions and submitted a PR to bioconda
https://github.com/bioconda/bioconda-recipes/pull/33628

Best
Andrey
