### ISSUE TITLE
Reference-based and model-based TPMs are vastly different

### ISSUE THREAD

**Issue by siyer-broad** [ablab/IsoQuant#249]
This could be related to Issue #248

I am using Isoquant v3.6.1 with a reference as well as in discovery mode. This is the command line I use
`/usr/local/bin/isoquant.py \ 

    --reference Homo_sapiens_assembly38.fasta \
    --genedb gencode.v38.primary_assembly.annotation.db \
    --complete_genedb \
    --bam <minimap2-aligned sorted bam> \
    --data_type pacbio_ccs \
    --stranded forward \
    --transcript_quantification unique_splicing_consistent \
    --model_construction_strategy fl_pacbio \
    --gene_quantification unique_splicing_consistent \
    --report_canonical all \
    --report_novel_unspliced false \
    --threads 8 \
    --labels test1 \
    --prefix test1 \
    --output isoquant_output \
    --counts_format both `

I get the full set of transcripts in the reference GTF in `transcript_tpm.tsv` (237014) but in `transcript_model_tpm.tsv` there were only 21627 lines.
Besides, while there is overall correlation(ish) there are significant discrepancies in the outputs between the two outputs - In the plot attached, X axis is reference-based TPM and Y axis is model-based TPM. Blue line is x=y line
![image](https://github.com/user-attachments/assets/53d69b52-577e-4ec0-8b5d-3be1c53315f9)

Is this expected?

**Comment by siyer-broad** [comment]
Thank you for your response. And the excellent tool.

**Comment by camelest** [comment]
@andrewprzh @siyer-broad Hi, thank you so much for the great tool and the detailed discussion.

I'm facing the same situation. Is it reasonable to perform another round of IsoQuant using `OUT.transcript_models.gtf` as reference to obtain consistent quantification between known and novel transcripts?

**Comment by andrewprzh** [comment]
@camelest 

In general yes, you can do that. I am pretty sure that results will be a bit different.

Overall, I think it's normal. Reference-based quantification simply assigns reads to transcripts and then does the counts. It does not have any sophisticated methods to check whether the transcript is reliable enough to report.
Model construction algorithm, on the other hand, is more conservative and reports only reliable transcripts.
As I mentioned, my experience on simulated data shows that both methods yield similar correlation with the ground truth, but have certain differences among themselves.  

P.S. It's sometimes easy to miss a comment in a closed issue.

Best
Andrey

**Comment by camelest** [comment]
@andrewprzh 
Thank you so much for the clarification. Sorry, I will open a new issue next time. 
The tool is really great! Thank you again for your kind support.

Best,

**Comment by andrewprzh** [comment]
You are welcome! No problem - it's just possible that I'll answer new issue faster :)

**Comment by dudududu12138** [comment]
Hi, I have a new question about your discussions above. I have two reference annotations A and B and they share most common transcripts while they also have some private transcripts. Then I ran reference based quantification with the two annotations separately. Will the quantification results same between the common transcripts both in A and B?

**Comment by andrewprzh** [comment]
@dudududu12138 replied in https://github.com/ablab/IsoQuant/issues/273
