### ISSUE TITLE
Confusion with results of exon quantification.

### ISSUE THREAD

**Issue by zhou-ran** [ablab/IsoQuant#25]
Hi all,

I tried to use IsoQuant to process my nanopore with count_exons mode, but some of exon was come from multiple genes in `exon-counts.tsv` file. like below

```
1	30940302	30943323	-	XSM	ENSMUSG00000117310,ENSMUSG00000026064	NA	0	705
1	30940303	30943323	-	XSCU	ENSMUSG00000117310	NA	15	690
1	30941580	30943323	-	XCU	ENSMUSG00000117310	NA	97	576
1	30941947	30943323	-	XCU	ENSMUSG00000026064	NA	24	601
1	30943221	30943323	-	XCU	ENSMUSG00000026064	NA	1	370
1	30943932	30944006	-	ICM	ENSMUSG00000117310,ENSMUSG00000026064	NA	342	15
1	30943932	30944304	-	XU	ENSMUSG00000026064	NA	0	357
1	30944536	30944666	-	IM	ENSMUSG00000117310,ENSMUSG00000026064	NA	336	20
1	30944938	30945030	-	ICM	ENSMUSG00000117310,ENSMUSG00000026064	NA	334	15
1	30944938	30946426	-	XU	ENSMUSG00000026064	NA	0	355
1	30946038	30946636	-	ISCU	ENSMUSG00000117310	NA	21	332
1	30946038	30946639	-	ISM	ENSMUSG00000117310,ENSMUSG00000026064	NA	72	281
1	30948997	30949309	-	XU	ENSMUSG00000026064	NA	0	103
1	30949549	30949755	-	XSCU	ENSMUSG00000117310	NA	9	94
1	30949549	30949757	-	XSCU	ENSMUSG00000117310	NA	26	77
1	30949549	30949770	-	XU	ENSMUSG00000117310	NA	4	99
1	30949584	30949691	-	XCU	ENSMUSG00000117310	NA	0	102

```

In full length sequence, we've known that each exon originates from which gene. Maybe we could quantify the expression of exon more precisely after we assigned identity of each read?

Thanks
Ran

**Comment by andrewprzh** [comment]
Dear Ran

Unfortunately, current exon/intron quantification method is quite naive - it doesn't account the specific isoform the read was assigned to. The exon count table simply shows which genes include the exon and how many reads cover it (regardless of the assigned gene).

Currently, the possible ways to derive gene-specific exon counts are
- to use .read_assignments.tsv that provides information for every read independently and count exon abundances manually
- to use transcript_counts.tsv that stores abundances for every transcript, but does not state whether all exons were covered or not.

I'll consider implementing another quantification method in the future releases, thank you!

Best
Andrey

**Comment by zhou-ran** [comment]
Hi Andrey, 

Thank you for your time and i look forward to your new release.

Cheers
Ran
