### ISSUE TITLE
Some reads are not recorded in the OUT.read_assignments.tsv.gz

### ISSUE THREAD

**Issue by creaturemoon** [ablab/IsoQuant#261]
Hello,
    I used isoquant3.6.1 with the command `isoquant.py --reference /path/to/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa --bam primaryalign.sort.bam  -o txquantify --model_construction_strategy default_ont --gene_quantification unique_only --transcript_quantification unique_only --splice_correction_strategy default_ont --genedb /path/to/genome.gtf --data_type nanopore --no_model_construction --threads 4` to quantify the abundance the transcripts. However, some reads in the primarily mapped bam file did not appear in the output `OUT.read_assignments.tsv.gz` file. In Python, the aligned chromosomes of these reads start with `#`, but with the code `read.reference_name` the aligned chromosomes are normally displayed, and they are normal using `samtools view`. Here is an example of one of the reads `c4e0190a-6474-4007-997b-d868cf363f4e` and a test bam file containing this read. 
![image](https://github.com/user-attachments/assets/775b5be1-4079-4943-9fe1-63c92fca4551)
![image](https://github.com/user-attachments/assets/84effc8f-970d-44bf-b826-cc7ac66653dd)
[testsam.zip](https://github.com/user-attachments/files/17799856/testsam.zip)

Could this be the reason these reads have not been documented? I look forward to your reply.

**Comment by andrewprzh** [comment]
Dear @creaturemoon 

IsoQuant filters out low-quality primary alignments that are not consistent with the reference annotation. The read in your example has MAPQ 0, so likely it is the case. You change it by setting `--inconsistent_mapq_cutoff 0`.

Hope that helps!

Best
Andrey

**Comment by creaturemoon** [comment]
I see. Thanks for your help.
