### ISSUE TITLE
Help Understanding "SAMPLE_ID.novel_vs_known.SQANTI-like.tsv"

### ISSUE THREAD

**Issue by cedric-k-n** [ablab/IsoQuant#264]
Hello!
  Thank you very much for your work on this great tool!

   I am master student new to data science research. I am using IsoQuant to discover novel transcripts, and I am not sure if I understand one output file correctly "SAMPLE_ID.novel_vs_known.SQANTI-like.tsv". I ran IsoQuant using the following script: 
`isoquant.py -t 32 --reference GRCh38_no_alt_analysis_set.fa --genedb gencode.v43.annotation.gtf --complete_genedb --bam Sample.bam --data_type nanopore --check_canonical --sqanti_output --prefix sampleID -o /isoquant_out/`

   I enabled `--sqanti_output` to get the "SAMPLE_ID.novel_vs_known.SQANTI-like.tsv" file in my output directory. I counted the number of unique categories from one sample file: 
   72 full_splice_match
    223 incomplete_splice_match
   5884 intergenic
      7 mono_exon_match
   4554 novel_in_catalog
  31655 novel_not_in_catalog
 
  Are these transcripts all novels? How do I determine the true number of novel isoforms?  It seems to me that there are some artifacts in this count. I was able to count the total number of reference matched + novel for this sample from the "SAMPLE_ID.transcript_models.gtf" file by doing: 

`cut -f 3 SAMPLE_ID.transcript_models.gtf | grep "transcript" | wc -l` 

Output: 86021

   Ideally, I am trying to count 1)total number transcripts, 2) total number of known transcripts, and 3) total number of novel transcripts. Similar to the supplementary data in your 2023 isoquant paper. 

   I will great appreciate any advice you could suggest.

  Thanks!

**Comment by andrewprzh** [comment]
Dear @cedric-k-n 

The easiest way to get transcript counts is to check the `isoquant.log` file, it has this information in the end.
Total novel count is the sum of novel not in catalog and novel in catalog. 

SQANTI-like output contains only novel transcripts and their comparison to annotated isoforms. The detailed explanation can be found in [SQANTI repo](https://github.com/ConesaLab/SQANTI3/wiki/Understanding-the-output-of-SQANTI3-QC#classifcols).

Hope that helps!

Best
Andrey

**Comment by cedric-k-n** [comment]
Dear Andrey,

Thank you very much for providing this feedback! I was able to find transcript counts in the isoquant.log file and an even information about the poly(A) tail length! 
 
 Thanks again for the help and for making this great tool!

  Best,
 
  Cedric
