### ISSUE TITLE
Problem with db creation from gencode gtf

### ISSUE THREAD

**Issue by samuelecancellieri** [ablab/IsoQuant#27]
Hi,
I'm receiving this error when the software starts the generation of the db from the gencode gtf.

Traceback (most recent call last):
  File "/home/samuele.cancellieri/.conda/envs/rna-seq/bin/isoquant.py", line 486, in <module>
    main(sys.argv[1:])
  File "/home/samuele.cancellieri/.conda/envs/rna-seq/bin/isoquant.py", line 480, in main
    run_pipeline(args)
  File "/home/samuele.cancellieri/.conda/envs/rna-seq/bin/isoquant.py", line 452, in run_pipeline
    args.genedb = convert_gtf_to_db(args)
  File "/home/samuele.cancellieri/.conda/envs/rna-seq/share/isoquant-2.2.1-0/src/gtf2db.py", line 108, in convert_gtf_to_db
    gtf_filename, genedb_filename = convert_db(gtf_filename, genedb_filename, gtf2db, args)
  File "/home/samuele.cancellieri/.conda/envs/rna-seq/share/isoquant-2.2.1-0/src/gtf2db.py", line 156, in convert_db
    convert_fn(gtf_filename, genedb_filename, args.complete_genedb)
  File "/home/samuele.cancellieri/.conda/envs/rna-seq/share/isoquant-2.2.1-0/src/gtf2db.py", line 94, in gtf2db
    gffutils.create_db(gtf, db, force=True, keep_order=True, merge_strategy='merge',
  File "/home/samuele.cancellieri/.conda/envs/rna-seq/lib/python3.9/site-packages/gffutils/create.py", line 1292, in create_db
    c.create()
  File "/home/samuele.cancellieri/.conda/envs/rna-seq/lib/python3.9/site-packages/gffutils/create.py", line 506, in create
    self._init_tables()
  File "/home/samuele.cancellieri/.conda/envs/rna-seq/lib/python3.9/site-packages/gffutils/create.py", line 438, in _init_tables
    self.set_pragmas(self.pragmas)
  File "/home/samuele.cancellieri/.conda/envs/rna-seq/lib/python3.9/site-packages/gffutils/create.py", line 425, in set_pragmas
    c.executescript(
sqlite3.OperationalError: database is locked

I don't know why this error is generated, since the db is created automatically by the software.
Can you help me with this?

Thanks a lot.

Best,
Samuele

**Comment by andrewprzh** [comment]
Dear Samuele

This looks like a problem in SQLite, which is used for gene database storage. It seems that this particular database is locked (e.g. some other database connection is active). So it's not an IsoQuant bug as well :)

Could you try running IsoQuant again with --clean_start option? If it doesn't help you may also try restarting you bash session. 
Let me know if any of those works.

Best
Andrey

**Comment by samuelecancellieri** [comment]
I will try with the clean_start, thanks.
But the db is generated by isoquant, is not already in the directory, I just give a gtf as input.

I will let you know.
Thanks.

**Comment by andrewprzh** [comment]
Yes, but if this GTF was previously converted, IsoQuant will detect the .db file and use to avoid unnecessary conversion.

Best
Andrey

**Comment by samuelecancellieri** [comment]
Hi @andrewprzh,
I've tried removing the out_dir and recomputing from scratch with the clean option.
But I get the same error.
The db file is not present, and it's generated by isoquant in the out_dir and if I understood correctly this is done when no db is found to use.
The software was installed with conda, and it's version 2.2.1.

Attached
[isoquant.log](https://github.com/ablab/IsoQuant/files/8715963/isoquant.log)
[isoquant.e8537775.txt](https://github.com/ablab/IsoQuant/files/8715964/isoquant.e8537775.txt)
[isoquant.o8537775.txt](https://github.com/ablab/IsoQuant/files/8715965/isoquant.o8537775.txt)

Thanks a lot for any help.

**Comment by andrewprzh** [comment]
@samuelecancellieri 

From what I read on the similar issues, it seems that SQLite doesn't allow to create or write into a database on a remote storage, i.e. NFS share. I presume you are using the one for the output folder, right?
`--output /shares/CIBIO-Storage/GROUPS/sharedNB/gtex_out/out_isoquant/`

If so, I'd suggest to use another output disk if possible. If you have limited space you may also convert GTF to DB using this script https://github.com/ablab/IsoQuant/blob/master/src/gtf2db.py
`python gtf2db.py -i /shares/CIBIO-Storage/GROUPS/sharedNB/gtex_input/annotation/gencode.v40.chr_patch_hapl_scaff.annotation.gtf  -o gencode.v40.chr_patch_hapl_scaff.annotation.db  --complete_genedb`
and then move the .db file to your storage. As far as I understand, read operations are allowed by SQLite from shared storage.

Sorry for inconvenience, hope this helps!

Best
Andrey

**Comment by samuelecancellieri** [comment]
Hi @andrewprzh 
thanks a lot for the support, i managed to generate a correct db and the execution of isoquant worked fine with the alignment phase.
but after that, i receive this error (attached log file).
can you help me with that? the db is on a non-shared hard drive and was created starting from a gencode annotation gtf (http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/gencode.v40.primary_assembly.annotation.gtf.gz) usign the command you suggest in the previous comment.

thanks a lot for all the help.

Best,
Samuele
[isoquant.e8540591.txt](https://github.com/ablab/IsoQuant/files/8753049/isoquant.e8540591.txt)
[isoquant.o8540591.txt](https://github.com/ablab/IsoQuant/files/8753050/isoquant.o8540591.txt)

**Comment by andrewprzh** [comment]
Dear @samuelecancellieri 

I've never seen this error before. This is very odd, especially taking into account that sample 1 was successfully processed with the same database. From what I read it may possible be raised by lack of RAM.

I cannot guarantee the success, but you may try the following to reduce RAM consumption:
- Reduce the number of threads
- Use CHR Gencode annotation (https://www.gencodegenes.org/human/) instead of primary_assembly, which contains a lot of scaffolds and patches (unless you really need those)

Let me know if any of these helps!

Best
Andrey

**Comment by samuelecancellieri** [comment]
Hi @andrewprzh 
thanks for the fast answer.

I will try by reducing the threads and giving more RAM to the job.
But I've checked the annotation and the difference between the primary one and the reference, it's less than a thousand lines.

A question on the restart, it's possible to avoid the alignment phase?
Since I have all the alignments in the out directory, there's a way to avoid that phase?

Thanks a lot,
Samuele

**Comment by andrewprzh** [comment]
@samuelecancellieri 

I see, then changing GTF won't make a big difference. Chr reference has also a smaller FASTA file (which is loaded into the memory), but I doubt it will have a huge impact as well since each chromosome is loaded in a separate thread. 

Yes, if you provide previously aligned FASTQs, IsoQuant should detect corresponding BAM files automatically and skip the alignment step. This is possible if you provide the same reference genome and annotation, and you have not moved or renamed the previous output folder. So simply run the same command with fewer threads and another output folder.
If this does not work, you can similarly create BAM file list and provide it via --bam_list option. The BAM files are listed in the isoquant.log file.

Best
Andrey

**Comment by andrewprzh** [comment]
@samuelecancellieri 

For future runs, IsoQuant now has additional option `--genedb_output` for setting a separate folder for gene database in case main output folder is on shared disk. Thank you for your report!

Best
Andrey

**Comment by samuelecancellieri** [comment]
hi @andrewprzh 
thanks a lot for the update and the new flag.

right now the software is working fine, but reducing the used thread from 40 to 20, increase a lot the execution time.
the script is running in the cluster for more than 5 days and the first sample is not completely analized.
this is the command i used (i've redone the alignment to make sure everything worked fine from the beginning)

isoquant.py --output $out_dir --genedb $db_file --reference $genome_file --fastq_list $fastq_list --data_type nanopore --matching_strategy precise --splice_correction_strategy default_ont --model_construction_strategy sensitive_ont --threads $threads --sqanti_output

maybe all this flags make the execution to slow?
thanks a lot for any suggestion on speeding up the analysis.

Best,
Samuele

**Comment by andrewprzh** [comment]
Hi @samuelecancellieri 

That's unusual. Using 20 threads allowed me to process datasets with 100M+ reads within a day. How large is your dataset?
Could you send me log, please?

The only option that can lead to minor slowdown is `--sqanti_output`, but I doubt it has a drastic effect.

Can also be a I/O issue, like a slow disk read/write speed. Could be a bug that leads to stalling, but I have never encountered such a behavior. Anyway, better take a look at the log first.

Best
Andrey

**Comment by samuelecancellieri** [comment]
hi @andrewprzh 
sorry for the late response.

here the command, later in the past week the command return a core dumped error on the cluster, so now i'm testing it on a single server, maybe something is not working properly on the cluster.

Command line: /home/samuele.cancellieri/.conda/envs/rna-seq/bin/isoquant.py --output /shares/CIBIO-Storage/GROUPS/sharedNB/gtex_out/out_isoquant/ --genedb /home/samuele.cancellieri/data_for_analysis/gencode.v40.primary_assembly.annotation.db --reference /shares/CIBIO-Storage/GROUPS/sharedNB/gtex_input/genome/GRCh38.primary_assembly.genome.fa --fastq_list /shares/CIBIO-Storage/GROUPS/sharedNB/gtex_analysis/paths/trimmed_fastq_path_sample-related_terminated_line.txt --data_type nanopore --matching_strategy precise --splice_correction_strategy default_ont --model_construction_strategy sensitive_ont --threads 20 --sqanti_output

thanks a lot for any suggestion or help.

best,
Samuele

**Comment by andrewprzh** [comment]
Hi @samuelecancellieri 

The command line looks OK. I'm not sure `--matching_strategy precise` gives the best results for ONT reads - I'd recommend stick to default one, but this should not lead to an error. Core dump sounds like a failure in some internal library. Do you have the log and the error message from failed run?

Best
Andrey

**Comment by samuelecancellieri** [comment]
hi @andrewprzh 
sorry but i accidentaly delete all the logs when cleaning the directory from other jobs.
now i'm running the pipe on the lab server, to see if the problem is due to some HPC job scheduling.

thanks a lot for all the support.

**Comment by andrewprzh** [comment]
Please, reopen if the problem still exists.
