### ISSUE TITLE
assignment of inconsistent reads

### ISSUE THREAD

**Issue by imilenkovic** [ablab/IsoQuant#28]
Hello,

Thanks a lot for developing this very handy tool!

I have one question regarding the assignment of reads. In my output folder, I took a look at the file.transcript_tpm.tsv file and saw the TPM values for some of my transcripts of interest. I then looked at the file.read_assignments.tsv and saw that there are quite a few reads that were associated to some of the transcripts that had 0 TPM. I noticed that all of these reads were labelled as "inconsistent" in their read_ID-transcript_ID associations.

I should note that I previously filtered out all the ambiguous reads from the bam files, because I want to only keep the ones mapping strictly to one transcript.

Now, based on this, I assume that the reads that are used to make the TPM values are only the ones that are labelled as "unique" or "unique_minor_difference". **Is there a way to rerun isoquant and make it also include the reads labelled as inconsistent**, so that those transcripts also end up in the file.transcript_tpm.tsv file?

Thank you very much in advance!

Best,
Ivan

**Comment by andrewprzh** [comment]
Dear Ivan

Thank you for the feedback!

Inconsistent reads are considered to be potential novel alternatively spliced isofoms. In read_assignment.tsv file these reads are assigned to the most similar reference isoform, but still have major differences (i.e. extra exons, extra introns, alternative donor/acceptor sites etc). Most likely, they do not originate from the assigned reference transcripts (but rather from some unknown transcript) and thus are excluded from the quantification. Are you sure you'd like to count such reads for estimating expression of reference transcripts?

If so - I can implement such option, since I was about to make another minor release soon.

Best
Andrey

**Comment by imilenkovic** [comment]
Dear Andrey,

Thanks a lot for you answer.

This is an example from the read assignment file:

```
911b3a62-88d4-41a2-8799-93043b3fb9cc    chr1    -       ENST00000686025.1       ENSG00000009307.17
      inconsistent    alternative_polya_site_left:114718033   114718043-114718216,114718613-114718745,114719579-114719742,114720539-114720717,114723883-114723935     PolyA=True; Classification=novel_not_in_catalog;
```

In this case, if the read is not counted because of the alternative poly A site, I would rather keep it than discard it - would this make sense?

Thanks a lot in advance!

Best,
Ivan

**Comment by andrewprzh** [comment]
Dear Ivan

Yes, I agree, reads with alternative polyA or TSS that have the matching intron chain can be treated as the ones belonging to the reference isoform. But keep it in mind when you get to biological interpretation step :)

I'll try to implement this feature and make a new release during next week - will keep you updated.

Best
Andrey

**Comment by imilenkovic** [comment]
Dear Andrey,

That sounds great, please let me know when you make the new release :) thank you very much!

Best,
Ivan

**Comment by andrewprzh** [comment]
Dear @imilenkovic 

I've released the new version 2.3.0: https://github.com/ablab/IsoQuant/releases/tag/v2.3.0 (should be available via bioconda by now).
You can run IsoQuant with `--transcript_quantification with_inconsistent`. Should perform as we discussed.

Best
Andrey

**Comment by imilenkovic** [comment]
Hi Andrey,

Thanks a lot for this, I'm looking forward to try it out! What is the easiest way to install the new release - can I do it through conda?

Best,
Ivan

**Comment by andrewprzh** [comment]
Ivan

Yes, bioconda pull request was approved just recently so 2.3.0 should be available on conda by now. 

Best
Andrey

**Comment by imilenkovic** [comment]
Hey Andrey,

I made a new conda environment I called isoquant_new:
`conda create -c conda-forge -c bioconda -n isoquant_new python=3 isoquant`

and when I activated the new environment and tried running the software, it gave me this error:
`isoquant.py: error: unrecognized arguments: --transcript_quantification with_inconsistent`

Should I install it in a different way?

Best,
Ivan

**Comment by andrewprzh** [comment]
Hi Ivan

Seems that conda still has previous version 2.2.2, probably will take couple days to update.
Alternatively you can download the release https://github.com/ablab/IsoQuant/releases/tag/v2.3.0 or clone the repository.

Best
Andrey

**Comment by andrewprzh** [comment]
Hi Ivan

The second read has a different intron chain (i.e. alternative_structure_novel:114734208-114736777), so it won't be counted anyway.

The first one has also fake_terminal_exon_3 event, but it should not be treated as read belonging to a novel isoform. I agree this one should be included. I'll do some more checks on my changes and get back.

Best
Andrey

**Comment by imilenkovic** [comment]
Hi Andrey,

Do you maybe have some update on this? I was redoing some analyses and realized a whole isoform is excluded from the final tpm list because of being labelled as inconsistent (alternative_polya_site_left) even when using --transcript_quantification with_inconsistent.

Thanks a lot in advance!
Best,
Ivan

**Comment by andrewprzh** [comment]
Dear @imilenkovic 

Sorry for the delay, been a bit off for quite a while.

I did realize that IsoQuant has additional checks. For example, the isoform is reported only if it has at least one uniquely and consistently assigned read. 
This should be fixed in this branch https://github.com/ablab/IsoQuant/tree/isoquant_2.3.1

If you prefer using bioconda, I'll publish this release and also include these fixes in IsoQuant 3.0 that comes out soon.

Best
Andyre

**Comment by andrewprzh** [comment]
Dear @imilenkovic 

Should be fixed in IsoQuant 3.0 now.

Best
Andrey

**Comment by imilenkovic** [comment]
Hi Andrey,

Thanks a lot for letting me know! I will give it a go. 

Best,
Ivan

**Comment by andrewprzh** [comment]
@imilenkovic 

I'll close the issue for now, re-open if you encoutner any other problems with IsoQuant.

Best
Andrey
