### ISSUE TITLE
aggregated gtf file?

### ISSUE THREAD

**Issue by ANeueder** [ablab/IsoQuant#32]
Hi,
I've been running isoquant succesfully so far. Looks quite good so far.
The isoquant output contains gtf files per input file. These include also the novel transcripts.
Questions: 1) Is there a way to generate a gtf file across all input samples? Something that corresponds to the aggregated counts/TPM per group?
2) What's the nomenclature for the novel transcripts? Does it start with 1 to X for the first sample and then continue in the second and so on?
Thanks for your help!
Best,
Andreas
PS: Something I've noticed is that it generates massive temp data. In the range of 600 GB and upwards for 9 samples. Not a problem, just maybe something you want to put in the help file so users are aware.

**Comment by ANeueder** [comment]
Hi Andrey,
Great and many thanks for the quick reply.
I will try with what you have suggested. Wasn't clear to me from the manual that --read_group would generate individual reads even when everything is treated as one sample.
Best,
Andreas

**Comment by ANeueder** [comment]
[isoquant.sh.ts-out.hUCoxs.log](https://github.com/ablab/IsoQuant/files/8935406/isoquant.sh.ts-out.hUCoxs.log)

Hi Andrey,
So, I've tried to run everything as 1 sample (24 bams) with the --read_group file_name option.
Unfortunately, it kills the process at some point, see attached log file.
Happened twice at exactly the same stage.
The only thing I've changed from the individual replica is the bam_file_list. Command and options are the same.
Do you have an idea? Much appreciated!
Best,
Andreas

**Comment by andrewprzh** [comment]
Dear Andreas

That's a very weird-looking bug as exception seem to occur outside of IsoQuant code. We searched for similar problems and we possibly may have a fix: https://github.com/ablab/IsoQuant/commit/9b05ecd8345a00b88e25282729a248cce87aa7f8.
Could you try IsoQuant from this GitHub repository (not Conda)? If you need any help write me via email. 

Best
Andrey
