### ISSUE TITLE
hanging run due to threading, option to run unthreaded

### ISSUE THREAD

**Issue by derijkp** [ablab/IsoQuant#37]
Hi,

Some isoquant runs have been hanging indefinitely. strace showed processes were stuck on a futex call, which is indicative of a race condition in python multiprocessing. I tried using 1 thread, which did not solve the problem (still uses a master and 1 worker thread).
Removing threading(multiprocessing) by replaceing the pool starmap by itertools starmap in data_processor.py did solve it though (no further hanging jobs)

As a workaround (race conditions are notoriously difficult to solve, esp. if they don't reproduce on your own datasets/systems. ), Would it be possible to add running unthreaded as an option.  (We distribute over regions ourselves anyway in order to be able to run on different nodes in the cluster.)

Regards,

Peter

**Comment by andrewprzh** [comment]
Dear Peter

Sorry for the delayed response and thank you for digging into the issue.

Unfortunately, we have not encountered such a behavior ourselves. 3.0 is still an alpha release, so we will at least switch to itertools startmap at least. Thanks a lot for the suggestion, I'll keep you updated!

Best
Andrey

**Comment by andrewprzh** [comment]
Dear @derijkp 

We've implemented a proper single-thread mode without using thread pools in 3.0, so you are welcome to try it out.

Best
Andrey

**Comment by andrewprzh** [comment]
@derijkp will close this issue for now, please re-open if any you still have any problems with IsoQuant.

Best
Andrey
