### ISSUE TITLE
Why decimals appear in counts.tsv?

### ISSUE THREAD

**Issue by kir1to455** [ablab/IsoQuant#40]
Hi, andrewprzh
I have a new question about the counts.tsv output file, I found that these counts are followed by decimals.
Generally speaking, these counts are read counts, which should be integers.
![image](https://user-images.githubusercontent.com/87375686/190941599-49727223-a2ea-41fb-a154-ded46fb34cf1.png)
Why do decimals appear in these counts file?
![image](https://user-images.githubusercontent.com/87375686/190941617-4f2c739d-76f6-4028-a6fb-2058f89ff59a.png)

Thanks for your help!
Best,
Kir1to455

**Comment by andrewprzh** [comment]
Hi @kir1to455 

I'm sorry for not replying earlier, somehow missed your reply in another thread.

Non-integer counts arise from ambiguous reads that were assigned to several transcripts simultaneously. If you want those to be ignored during quantification you can set `--transcript_quantification unique_only`.

Hope that helps!

Best
Andrey

**Comment by paulimer** [comment]
Just a small update on this : by default, transcript counts are indicated in the README that `--transcript_quantification unique_only` is the default, yet I still see counts with decimals, is this expected? (By the way there is a misprint in the Quantification header)

Thanks!

![image](https://user-images.githubusercontent.com/72985844/215492123-f0b00043-8ef5-466c-89d5-68b7cd27a23d.png)

**Comment by andrewprzh** [comment]
Dear @paulimer 

Sorry for the confusion, I forgot to fix the readme, the default quantification strategy for transcripts is now `with_ambiguous`. Based on our experiments it gives somewhat more accurate estimates of expression level. Will fix the manual, thanks for bringing my attention.

Best
Andrey
