### ISSUE TITLE
bootstrapping

### ISSUE THREAD

**Issue by rsalz** [ablab/IsoQuant#45]
Hi Andrey! I have another suggestion.
I am working with a pilot dataset with 1 long read (pacbio) sample per condition. Considering this limitation in data, I am thinking of how best to quantify.
It would be nice if you built in some additional tools for normalization (e.g. TMM), filtering, bootstrapping.
Not sure if this is within the scope of this tool but would be nice. If it's outside the scope, what would you suggest as a follow-up to isoquant?
Interested to hear what you think

**Comment by andrewprzh** [comment]
Dear @rsalz 

Unfortunately, this functionality was never on out list, IsoQuant is more of a upstream tool for getting raw counts.
To be honest, I have no experience with 1 replica-per-condition cases. EdgeR vignette has some suggestions on this topic, I guess (section 2.12, https://bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf).

Best
Andrey
