### ISSUE TITLE
problems with sqanti output

### ISSUE THREAD

**Issue by tabeariepe** [ablab/IsoQuant#47]
Hi,

I run isoquant with `--sqanti_output `on my data and all output files contain results except for SAMPLE_ID.SQANTI-like.tsv. I also noticed that in the SQANTI files for the individual chromosomes the output is for each read and not for each isoform.

**Comment by andrewprzh** [comment]
Dear @tabeariepe 

Thank you for the report!

1. Empty output is a bug left from paralellization step - individual choromosomal files are not combined in the end. Will fix, thank you!
2. IsoQuant only produces SQANTI-like output for assigned reads, not for the resulting transcripts. For this purpose I suggest to run the latest SQANTI itself, as far as I know, it supports GTF as an input now.

Best
Andrey

**Comment by tabeariepe** [comment]
Hi Andrey, 

Why do you only produce the SQANTI-like output for the reads? I run SQANTI before on a TALON gtf file and I remember that `sqanti3_qc.py` also includes filtering and not only classification. So would it not be more convenient to produce a SQANTI-like output per isoform directly?

**Comment by andrewprzh** [comment]
I think the reasons are purely historic - initially IsoQuant designed for read-to-isoform assignment and classification.
Seems that producing classification for the final isoforms in SQANTI format is also doable, will add it on my TODO list :)

Best
Andre

**Comment by tabeariepe** [comment]
Great, thank you! This will be really helpful for me.

**Comment by rsalz** [comment]
This would be super helpful if you could get to this soon Andre!! This would be extremely helpful for integration in downstream analysis and for being able to show results to our genetics colleagues that are used to looking at SQANTI output. Please please prioritize this

**Comment by andrewprzh** [comment]
Dear @rsalz @tabeariepe 

Finally, IsoQuant 3.2 is released, it now has SQANTI output for novel transcripts.

Best
Andrey
