### ISSUE TITLE
Novel Isoforms Not Assigned to Genes

### ISSUE THREAD

**Issue by abidrehman2000** [ablab/IsoQuant#49]
I have noticed that when running IsoQuant with a BAM file input, that all of the novel isoforms are not assigned to any genes. The input data is ONT single-cell mice cDNA data. Are there any parameters that can be adjusted/fixed to correct for this?

**Comment by andrewprzh** [comment]
Dear @abidrehman2000 

I think it is possible that only novel genes are detected, but no novel isoforms for existing genes.
Could you please send you command line and isoquant.log file just in case?

Best
Andrey

**Comment by abidrehman2000** [comment]
Attached is the log file with the relevant command line at the top
[isoquant.log](https://github.com/ablab/IsoQuant/files/10271781/isoquant.log)

**Comment by andrewprzh** [comment]
Seems to be nothing wrong with the log, are you sure *no* novel isoforms are belong to existing genes?

What concerns me a bit is the number of novel isoforms reported: 
novel_not_in_catalog: 259685
What aligned did you use?

Best
Andrey

**Comment by abidrehman2000** [comment]
We used the reference mm10 genome and aligned with the minimap2 genome, prior to running IsoQuant on the command line.

**Comment by andrewprzh** [comment]
Seems to be nothing wrong. So are you sure absolutely no isoforms were assigned to known genes?

**Comment by abidrehman2000** [comment]
Dear Andrey, 

Thank you for the assistance. I realize now that the novel isoforms to indeed have gene assignments. Should said novel isoforms have only the 'inconsistent' assignment type, or others as well?

**Comment by andrewprzh** [comment]
Dear @abidrehman2000 

Thanks for the response!

>Should said novel isoforms have only the 'inconsistent' assignment type, or others as well?
Mostly yes. Can be also "ambiguous" (rarely, but still possible). For novel genes it will most likely be "noninformative" or "intergenic". 

Best
Andrey

**Comment by andrewprzh** [comment]
I'll close this issue for now, please re-open or open a new one if other questions arise.

Best
Andrey
