### ISSUE TITLE
Additional reads generated in output tsv files

### ISSUE THREAD

**Issue by abidrehman2000** [ablab/IsoQuant#50]
I have noticed that in the output "sorted.read_assignments.tsv" file, there are duplicate reads that have the same read_id's? The input is a single-cell mouse bam file.

**Comment by andrewprzh** [comment]
Dear @abidrehman2000 

This is normal as some reads may be ambiguously assigned to multiple isoforms with equal probability. 
Such reads should be marked as ambiguous or inconsistent.

Best
Andrey
