### ISSUE TITLE
how to output combined GTF and counts including novel isoforms from multiple samples?

### ISSUE THREAD

**Issue by jackhump** [ablab/IsoQuant#53]
Hello Andrey,

Congratulations on publishing Isoquant! I'm really excited to try using it in my long-read projects.

Similarly to issue #46 , I'm trying to run Isoquant across multiple samples in a single run, with the goal of outputting a single GTF and count matrix for all annotated and novel isoforms found across the samples, so that I can compare directly with the outputs of Bambu and Stringtie2. 

I'm currently using isoquant v3.0.3 from conda.

my isoquant command looks like this:

```
isoquant.py --data_type pacbio_ccs \
  --bam_list bam_list.txt \
  --read_group file_name \
  --reference genome.fa \
  --genedb gencode.annotation.db \
  --output results/ \
  --labels sample_1 sample_2 \
  --threads 16
```

I've tried a bam_list with or without newlines between the paths. 

1.

```
/path/to/sample1.bam:sample_1
/path/to/sample2.bam:sample_2
```
2.

```
/path/to/sample1.bam:sample_1

/path/to/sample2.bam:sample_2
```

Running with bam_list 1, which I believe was your suggestion in Issue #46 , treats both bams as coming from a single sample and outputs a TPM/count matrix only for that combined sample, rather than a matrix with values for the two samples separately.

Running with bam_list 2 correctly identifies two distinct samples, but creates two separate `.extended_annotation.gtf` files and produces `combined_gene` and `combined_transcript` matrices only for annotated isoforms, as far as I can tell.

Can you guide me on what I need to do to generate a single combined GTF and count/TPM matrix including both novel and annotated isoforms?

Thanks!
Jack

**Comment by andrewprzh** [comment]
Dear @jackhump 

Sorry for the delayed responce. Does you output folder contain files ending with `transcript_model_grouped_counts.tsv` and `transcript_model_grouped_tpm.tsv`?
These files should contain "per-file" counts and TPMs. If they are not there, please send me the `isoquant.log`.

Let me know if this helps in any way!

All the best
Andrey

**Comment by jackhump** [comment]
Hi Andrey! Thanks for this, I didn't notice the `transcript_model_grouped_counts` files, this is great, thanks!

I'm looking through them now and I've noticed that isoquant has found 272,271 isoforms in my 30 PacBio libraries, of which 233,027 are classified as novel with respect to GENCODE v38. But if I look at the number of isoforms that have at least 1 samples with a count > 0,  193,348 isoforms have 0 counts in all 30 samples.  For the 39,244 annotated isoforms, 15,246 have 0 counts in all 30 samples. So where do these all-zero isoforms come from?

**Comment by andrewprzh** [comment]
Hi Jack

This is the bug in the previous versions that should be removed in 3.1.1 (which was released a couple days ago).
Isoforms with 0 counts are "candidate isoforms" the were filtered out later as unreliable. They should not appear in the resulting GTF file (*.transcript_models.gtf) or ungrouped counts, the bug was only affecting the output of grouped counts tables. 
So I'd suggest to remove/ingore these rows. 

Best
Andrey

**Comment by jackhump** [comment]
thanks Andrey, I just updated to 3.1.1 and the all-zero isoforms disappeared, thanks!

I spotted another bug though, the `.extended_annotation.gtf`  seems to have duplicate entires for certain isoforms:

```
chr1    IsoQuant        gene    817371  819837  .       +       .       gene_id "ENSG00000177757.2"; transcripts "2";
chr1    IsoQuant        transcript      817429  819837  .       +       .       gene_id "ENSG00000177757.2"; transcript_id "ENST00000326734.2"; exons "2"; 
chr1    IsoQuant        exon    817429  818202  .       +       .       gene_id "ENSG00000177757.2"; transcript_id "ENST00000326734.2"; exon "1";
chr1    IsoQuant        exon    818723  819837  .       +       .       gene_id "ENSG00000177757.2"; transcript_id "ENST00000326734.2"; exon "2";
chr1    IsoQuant        transcript      817429  819837  .       +       .       gene_id "ENSG00000177757.2"; transcript_id "ENST00000326734.2"; exons "2"; 
chr1    IsoQuant        exon    817429  818202  .       +       .       gene_id "ENSG00000177757.2"; transcript_id "ENST00000326734.2"; exon "1";
chr1    IsoQuant        exon    818723  819837  .       +       .       gene_id "ENSG00000177757.2"; transcript_id "ENST00000326734.2"; exon "2";
```

This doesn't affect every isoform, only a subset. This could be worth looking into.

**Comment by andrewprzh** [comment]
Dear Jack

Thanks a lot for the report! I looked and at the code and realized this bug appeared after I changed the naming of known isoforms from `transcriptXXX.known` to original transcript id from the reference annotation. 
Will fix in the next release.

Best
Andrey

**Comment by andrewprzh** [comment]
Dear @jackhump 

The issue with duplicated transcript entries should be fixed in https://github.com/ablab/IsoQuant/releases/tag/v3.1.2

Best
Andrey
