### ISSUE TITLE
Can't run on SIRVs

### ISSUE THREAD

**Issue by josiegleeson** [ablab/IsoQuant#54]
Hi, I want to run IsoQuant on my own SIRV data for QC but it doesn't seem to work.

I think its due to the SIRV annotation files only containing exons, but when I try and run it with your example titled 'PacBio FL reads; custom annotation in GTF format, which contains only exon features:' I still get a warning that says 'WARNING - No reads were assigned to isoforms, check your input files'. 

I've also tried running the example without a GTF reference as per 'Nanopore cDNA reads; no reference annotation:' but I get an error saying: 'isoquant.py: error: the following arguments are required: --genedb/-g

IsoQuant seems to run fine on my human data so there must be something wrong with my files..

Thanks for any help!

**Comment by andrewprzh** [comment]
Dear @josiegleeson 

Could you please send the command you are using and the log?

Meanwhile, I suggest you to check:
1. Annotation in GTF has the same chromosome names as in FASTA file. They are known to have different versions, e.g. multifasta or all SIRV "chromosomes" concatenated. You may try using files we were using in our analysis: https://zenodo.org/record/7121404#.Y8GC19JBwUE
2. IsoQuant version. IsoQuant 2 required gene annotation, annotation free mode was only available in IsoQuant 3 and later.

Hope that helps!

Best
Andrey

**Comment by josiegleeson** [comment]
Hi Andrey,

Thanks for your quick response! I was using an earlier version, git checkout latest seems to still give version 2. If I do git checkout master it fixes this.

I think my GTF doesn't work as only the exons are annotated, using your file seems to work now. Thank you.

**Comment by andrewprzh** [comment]
Hi @josiegleeson 

In fact, exon-only GTF should not be a problem. IsoQuant uses gffutils which is ok with parsing these kind of GTFs and inferring gene/transcript relations.

As for the `latest` tag, my bad, will update - thanks for noticing. I'd suggest using one of the following branches: `isoquant_3.0.3` or `isoquant_3.1.0`. Master branch is somewhat unstable.

Best
Andrey

**Comment by josiegleeson** [comment]
Ok I'll try with my other exon only GTFs.

And thanks for the advice I'll use 3.1.0. :)
