### ISSUE TITLE
Compatability w/ DESeq2 Differential Isoform Expression

### ISSUE THREAD

**Issue by NanoCoreUSA** [ablab/IsoQuant#55]
Hi, great work, looking forward to giving it a try!

After looking through the documentation / output files, it seems like the generated count data should pipe quite easily into DESeq2 for calling differential expression between samples. We are interested in identifying differential isoform expression and were wondering if you had any experience using IsoQuant to do this.

Thanks!

**Comment by andrewprzh** [comment]
Dear @NanoCoreUSA 

Thank you for the positive feedback!

Personally, I have not yet used IsoQuant for differential expression analysis, but I guess some of the users have.

I have some experience with DESeq2, and to my understanding count tables generated by IsoQuant should be just fine as DESeq2 input, i.e. rows are genes/isoforms and tables are samples/replicas. IsoQuant is also capable generating TPM tables, but I presume DESeq2 is fine with raw counts. 

Best
Andrey
