### ISSUE TITLE
How many “--genedb” allowed?

### ISSUE THREAD

**Issue by fangbohao** [ablab/IsoQuant#56]
I was wondering how many gene databases I could feed through “--genedb”. Only one right?

**Comment by andrewprzh** [comment]
Dear @fangbohao 

Yes, you are right, IsoQuant takes only a single gene annotation as an input.

If you need to use more that one, you may try using [gffcompare](http://ccb.jhu.edu/software/stringtie/gffcompare.shtml) tools that allows to merge multiple annotations.

Best
Andrey

**Comment by fangbohao** [comment]
> Thank you, Andrey, for your explanation!
