### ISSUE TITLE
CAGE data

### ISSUE THREAD

**Issue by rsalz** [ablab/IsoQuant#57]
I have the newest version of isoquant (3.1.1). In the "full help" it says that I can give CAGE peak data as input but I just tried to do that and I got the error: 
`2023-01-25 13:48:35,572 - CRITICAL - CAGE data is not supported yet`
why is it shown as an option if I cannot use it?

**Comment by andrewprzh** [comment]
Dear @rsalz 

CAGE data support is in progress, the option there was made for testing at some point, however, it is not described in the manual or in the main help. I will remove it in the next release to avoid further confusion. CAGE support itself will be implemented later.

Best
Andrey
