### ISSUE TITLE
Starting with a soft-maksed reference genome?

### ISSUE THREAD

**Issue by fangbohao** [ablab/IsoQuant#59]
Hi, I was wondering if I should run IsoQuant with a repeats-soft-masked reference genome or just an unmasked genome. Which one would be better?

Thanks!
Bohao

**Comment by fangbohao** [comment]
Also, could I concatenate FASTQ files from different tissues first, and then run isoQuant?

Thanks!

**Comment by andrewprzh** [comment]
Dear @fangbohao 

IsoQuant does not differentiate between lower and upper case, and so does not minimap2, which is used as the default aligner (https://github.com/lh3/minimap2/issues/654). I've always used unmasked genomes. I don't think repeats strongly affect mapping of RNA reads.

Yes, using all reads combined could be beneficial for discovery of low-expressed isoforms. You don't need to concatenate them, you can simply provide `--fastq_list file.txt`, were file.txt contains list of all FASTQs without blank lines. There couple examples in the manual.

Best
Andrey

**Comment by fangbohao** [comment]
Hi Andrey, thank you for your suggestions!

**Comment by fangbohao** [comment]
Hi Andrey, a follow-up question:
Once getting the resulting transcript, do you have any recommended programs/pipelines to conduct gene structure annotation? 

Thanks!

**Comment by andrewprzh** [comment]
I don't have much experience with further analysis. You may try looking into [IsoAnnotLite](https://isoannot.tappas.org/isoannot-lite/) and [tappaS](https://app.tappas.org/). 
They may require running SQANTI3. As far as I know current SQANTI version supports GTFs produced by other tools.
Next version of IsoQuant will also provide novel transcript classification in SQANTI-like format.

Best
Andrey

**Comment by fangbohao** [comment]
Thank you, Andrey!
