### ISSUE TITLE
What's the source of high memory usage?

### ISSUE THREAD

**Issue by jamestwebber** [ablab/IsoQuant#60]
Hi there! 👋 I'm interested in running IsoQuant on our [MAS-iso-seq](https://www.pacb.com/products-and-services/applications/rna-sequencing/single-cell-rna-sequencing/) data and I'm finding that it takes quite a while to get through the library (four flowcells merged together, so a fairly hefty dataset). I'm currently running with `--low_memory` but it is still taking quite a bit of time on a large instance (128 GB RAM) so I'm looking for some more help.

Do you have an idea of where the bottlenecks are in this pipeline? I'd be happy to take a crack at optimizing things a little if I can, but there's a lot going on here so if you have advice of where to start that'd be great.

Or, if there are any run-time tricks I can try to speed this up I could try that instead.

**Comment by jamestwebber** [comment]
Looking into the code more, I'm going to try to improve the performance of [this code](https://github.com/ablab/IsoQuant/blob/master/src/dataset_processor.py#L376-L392).

There are a few places where all the data is being collected in a list or tuple before the next step, and I think it can be rewritten to use generators throughout so that the whole dataset doesn't need to be in memory. Python can be tricky about this, particularly with multiprocessing.

I don't know if this will help much, but that seems to be where my run is struggling and I think a more streaming approach might reduce memory usage a fair amount. I'll update here after some tests.

**Comment by andrewprzh** [comment]
Hi @jamestwebber 

Thank you for your interest in the tool and, especially, the code. Getting good results was the number one priority, so the code might be quite sub-optimal in some cases. 

In the current release, `--low_memory` doesn't do much. At this very moment, I working right on it :) Especially, the [part](https://github.com/ablab/IsoQuant/blob/master/src/alignment_processor.py#L94) where reads are collected from BAM files. In this function, chunks of BAM files are stored in RAM to prevent multiple reading from disk. In "low RAM" mode there will be no such thing ([alpha version](https://github.com/ablab/IsoQuant/blob/master/src/alignment_processor.py#L172) is already in the master branch). I presume it is one of the possible bottlenecks.

I think I will finish with that within a few working days at most. If you'd like to talk about the code more you can write me directly via email! I would be happy to discuss potential technical improvements.

Best
Andrey

**Comment by jamestwebber** [comment]
Well I can confirm that the piece of code I was looking at is _not_ the cause. Although I think that's where I ran out of RAM last time, so maybe it's a small improvement.

**Comment by andrewprzh** [comment]
By the way, here is [PR](https://github.com/ablab/IsoQuant/pull/62) that improves low-memory mode. First part (read assignment) does take noticeably less RAM without taking much time in "low-memory" mode, at least on a simple example on my laptop with SSD disc. However, the second part (transcript construction) still takes quite some RAM.

These changes still require some testing, but you may take a look at that and give some suggestions if interested.
