### ISSUE TITLE
Problems running version 3.1.2

### ISSUE THREAD

**Issue by tabeariepe** [ablab/IsoQuant#63]
I just tried to run the newest version of Isoquant (3.1.2) and I got a few errors. Compared to version 3.1.1., the following arguments are not recognised anymore:

```
--check_canonical 
--transcript_quantification 
--gene_quantification 
--splice_correction_strategy
```

Moreover, I have a .txt file with the path to my bam files. I use different replicates and I previously used the notation from the documentation: `/PATH/TO/file.bam:replicate1`. This now causes the following error: `Exception: File format .bam:s1 is not supported! Supported formats: FASTQ, FASTA, BAM`

**Comment by andrewprzh** [comment]
Dear @tabeariepe 

Could you please send me the command line error log that you get when using these options? I just tried setting them and it seems to work fine.

Best
Andrey

**Comment by tabeariepe** [comment]
The other error that I get is:

usage: isoquant.py [-h] [--output OUTPUT] --genedb GENEDB [--complete_genedb]
                   [--reference REFERENCE] [--index INDEX]
                   (--bam BAM [BAM ...] | --fastq FASTQ [FASTQ ...] | --bam_list BAM_LIST | --fastq_list FASTQ_LIST)
                   --data_type {assembly,pacbio_raw,pacbio_ccs,nanopore}
                   [--stranded STRANDED] [--has_polya] [--fl_data]
                   [--full_help] [--test] [--threads THREADS]
                   [--labels LABELS [LABELS ...]] [--read_group READ_GROUP]
                   [--sqanti_output] [--count_exons]
                   [--matching_strategy {exact,precise,default,loose}]
                   [--model_construction_strategy {reliable,default,fl,all,assembly}]
isoquant.py: error: unrecognized arguments: --check_canonical --transcript_quantification unique_only --gene_quantification unique_only --splice_correction_strategy default_pacbio

**Comment by andrewprzh** [comment]
There is something wrong with you installation as the error message tells you are using IsoQuant 1.0.0:
File "anaconda3/envs/isoquant/share/**isoquant-1.0.0-**2/src/input_data_storage.py", line 119, in check_input_type

You may try creating new environment or removing and installing IsoQuant again.

Best
Andrey

**Comment by andrewprzh** [comment]
Great, let me know if you have any other issues!
