### ISSUE TITLE
Unable to handle large samples

### ISSUE THREAD

**Issue by abidrehman2000** [ablab/IsoQuant#64]
Hello,

When running IsoQuant, I have found that after several hours, IsoQuant simply stops writing files and seems to stop processing. For reference, I have been running IsoQuant using 30 threads, 200 GB, and 800 GB of Disk Space on an HPC system. Attached is the log file of IsoQuant, that contains all of the command line information used. 

Best,
Abid

[isoquant.log](https://github.com/ablab/IsoQuant/files/10724177/isoquant.log)

**Comment by andrewprzh** [comment]
Dear @abidrehman2000 

Yes, IsoQuant can get a little greedy in terms of memory consumption, we are working on it.

The log looks normal, so I presume it might disk I/O issue, or some large read chunk still being processed. For how long was it stuck? Does the process manager show that the process is still running / writing to disk? 

If the previous run has stopped, you can also try resuming the run using `--resume` option and setting fewer threads.

Best
Andrey

**Comment by abidrehman2000** [comment]
Dear Andrey, 

I looked over once more at the results, and I've noticed something intersting. 
For full context, I am currently running IsoQuant on an 800G RAM compute Node with 30 CPUS.
I have tried running IsoQuant a few times separately, but what appears to consistently happen is that after writing the results of a single sample (in my case, one that has three biological replicates), no new files are written. Currently, this seems to be the case after 12 hours.

I noticed that IsoQuant 3.1.1 has the fix _Fixed error when using a read grouping file._ Is it possible this fix might be causing issues?

Best,
Abid

**Comment by andrewprzh** [comment]
Dear @abidrehman2000 

We are currently working or RAM consumption. Meanwhile you can try setting fewer threads (works with --resume as well), let's say 4. 

The fix you've mentioned most like does not affect your run. There was an error, but as far as I understand you don't get any errors, you just run out of RAM.

Could you please send me the isoquant.log file so I can get some insights on what's going on?

Best
Andrey

**Comment by abidrehman2000** [comment]
Got it, I'll rerun it with 4 threads. I'm not sure if it's RAM consumption though since the RAM consumption report though doesn't seem to indicate as much.  Attached is both the log file, and a report of RAM consumption and CPU usage from the HPC cluster system
[isoquant.log](https://github.com/ablab/IsoQuant/files/10768826/isoquant.log)
![RAM_CONSUMPTION](https://user-images.githubusercontent.com/109555306/219709774-c5fbde87-2668-40f1-b42e-7546973b7cc8.png)

**Comment by andrewprzh** [comment]
Thanks for the indormation!

I now see that something fishy is going with chrM, which is usually processed very quickly (since it's small).
Is there a possibility to send me a BAM file with reads only mapping to chrM? I would also need the reference genome and the annotation, but you could just give a link. 

You can also write me directly via email.

Thank you!
Andrey

**Comment by andrewprzh** [comment]
Dear @abidrehman2000 

IsoQuant 3.2 was just released. Compared to previous version, it consumes ~10-15 times less RAM. Please, re-open the issue if you encounter the same problem in 3.2.

Best
Andrey

**Comment by itslittman** [comment]
I am experiencing the same issue on a fresh install.

**Comment by andrewprzh** [comment]
@itslittman which version do you use? Could you send me the log?

The only possibility I see at the moment is reducing the number of threads.

Best
Andrey
