### ISSUE TITLE
All assignment_type showed intergenic in read_assignment file

### ISSUE THREAD

**Issue by wang9685** [ablab/IsoQuant#66]
Hello,

IsoQuant versionL 3.1.2

I used ccs.fasta and reference.gtf as input, but I face several problems for my output data, and I am not sure if there are related.

1. All of _gene id_ and _transcript_id_ in transcript_model.gtf showed "_novel_gene_" and "_transcript1.chr1.nnic_".
2. All of  _assignment_type_ in read_assignments file showed _intergenic_, but we expected there would exist isoform in our data.

I also used BAM as input, but still got the same result.

Thank you!

**Comment by andrewprzh** [comment]
Hi @wang9685 

Based on what you say it seems that you have not provided reference annotation (GTF file). In this case IsoQuant runs de novo gene discovery and all genes/transcripts are reported as novel.

Could you send me the isoquant.log file to be sure?

Best
Andrey

**Comment by wang9685** [comment]
Hi, 

I have provided GTF file(mm39) as reference, so I have no idea why it couldn't get the information from GTF.

The attachment is log file.
[isoquant.log](https://github.com/ablab/IsoQuant/files/10751013/isoquant.log)

Thank you for your help!

**Comment by andrewprzh** [comment]
Dear @wang9685 

Based on the log file
`Command line: /mnt/data1/Tool/IsoQuant/isoquant.py -d pacbio_ccs --fastq /mnt/data2/Seqdata/20201006_PB/analysis/run3/CVLI1.ccs.fasta -r /mnt/data2/database/mm39/mm39.fa.gz --output output_dir`
you only provided reference genome in FASTA format, but no GTF. Hence, no known transcripts were dicovered because IsoQuant has no infromation on reference transcripts.

Best
Andrey

**Comment by wang9685** [comment]
Hi Andrey,

Sorry for my mistake. I attached the wrong file.
The following log file is the run with GTF as input.

[isoquant.log](https://github.com/ablab/IsoQuant/files/10763315/isoquant.log)

Thank you so much!

**Comment by andrewprzh** [comment]
Dear @wang9685 

Could send me your GTF file? In fact, a few lines would be enough.

I suspect that GTF may have different chromosome naming comapred to the FASTA file.

Best
Andrey

**Comment by wang9685** [comment]
Hi Andrey,

The attachment is GTF file.
[refGene.gtf.zip](https://github.com/ablab/IsoQuant/files/10772790/refGene.gtf.zip)

Thank you for your help!

**Comment by wang9685** [comment]
Hi Andrey,

Sorry for bothering you again. I am new at bioinformatics.
I am wondering  if there is something wrong for the reference GTF file.

Thank you so much!

**Comment by andrewprzh** [comment]
Dear @wang9685 

Sorry for a delay. Yes, you GTF does not have `gene` records, so you should re-run IsoQuant without `--complete_genedb` option. This should fix the problem.

Best
andrey

**Comment by wang9685** [comment]
Hi Andrey,

I tried this option, but it still generated the same result.
I changed the reference GTF and FASTA from UCSC version to GENCODE, the result was what we expected.

Thank you for all your help!

**Comment by andrewprzh** [comment]
Dear @wang9685 

Good to hear that! I'll check IsoQuant compatibility with UCSC annotations then at some point. Thank you!

Best
Andrey

**Comment by andrewprzh** [comment]
I'll close this issue for now. Please open a new one if other problems arise. 
I also suggest updating IsoQuant to 3.2.

Best
Andrey
