### ISSUE TITLE
Difficulty understanding relations between gtfs and counts

### ISSUE THREAD

**Issue by paulimer** [ablab/IsoQuant#67]
Hi,
I have some difficulty understanding the different gtfs in the output: the `SAMPLE_ID.extended_annotation.gtf` should include reference annotation + all discovered new transcripts, yet some discovered transcripts in the `SAMPLE_ID.transcript_model_grouped_counts.tsv` aren't present in in the extended annotation gtf, only in the `SAMPLE_ID.transcript_models.gtf` one. Is there a reason I'm missing for that?

I figured I should use the `SAMPLE_ID.transcript_counts.tsv`, but this one does not have novel transcripts at all.

Is there no `gtf` file with both reference annotation and novel transcripts corresponding to counts for both known and novel transcripts (the `model_counts.tsv` file if I am correct)?

Thanks in advance!

**Comment by andrewprzh** [comment]
Dear @paulimer 

`SAMPLE_ID.extended_annotation.gtf` should contain reference annotation + all novel transcripts dicovered.
`SAMPLE_ID.transcript_models.gtf` should contain all expressed transcripts (novel + known), so a subset of extended annotation.  If it's not a subset, it sounds like a bug. Could you send me isoquant.log and the output GTFs if possible?

With respect to counts, `SAMPLE_ID.transcript_model_grouped_counts.tsv ` and `SAMPLE_ID.transcript_model_counts.tsv ` corrspond to `SAMPLE_ID.transcript_models.gtf`, thus contain counts for novel isoforms.
`SAMPLE_ID.transcript_counts.tsv`, `SAMPLE_ID.gene_counts.tsv` are created before transcript discovery, so they contain information only about known transcripts, which can be useful for those who are interested only in expression analysis among known genes.

Hope this clarifies a bit, but don't hesitate to ask more questions. I think I might slightly change output folder structure to make it more transparent. 

Best
Andrey

**Comment by paulimer** [comment]
Dear @andrewprzh,
Here you can find the log, GTFs, and `model_grouped_counts` matrix : https://filesender.renater.fr/?s=download&token=330d5fbd-78a3-4c43-b378-64df15b59f14 . I have not done an extensive search of the transcripts present in the `transcript_models.gtf` and `model_grouped_counts.tsv` missing in the `extended_annotation.gtf`, but example of such cases are : transcript14756.KI270467.1.nnic, transcript9117.chr4.nnic, transcript2796.chr3.nnic, transcript17182.chr2.nnic. According to a downstream program I use (IsoformSwitchAnalyzeR), there are 111 such cases. 

As for the different counts files, that's what I figured! So it is not that confusing. Maybe the `model` name is not that clear, as one might expect only the novel isoforms in this file?

Just another small question, while processing all samples in a single read_group, to obtain a unique gtf (what I did here), would there be a way to specify the sample name? Or is there a way I have missed? Because here the `SAMPLE_ID` ends up being the name of the first bam in the `bam_list`.

Thanks in advance,
Paul

**Comment by andrewprzh** [comment]
Dear @paulimer 

Sorry for the delayed response!

>As for the different counts files, that's what I figured! So it is not that confusing. Maybe the model name is not that clear, as one might expect only the novel isoforms in this file?

I'll think about naming, however some users may already be using these names in the pipelines. 


>Just another small question, while processing all samples in a single read_group, to obtain a unique gtf (what I did here), would there be a way to specify the sample name? Or is there a way I have missed? Because here the SAMPLE_ID ends up being the name of the first bam in the bam_list.

Yes, you can provide file containing list of files with sample names after column using --bam_list, e.g.:
/PATH/TO/SAMPLE1/file1.bam:S1_REPLICATE1
/PATH/TO/SAMPLE1/file2.bam:S1_REPLICATE2
/PATH/TO/SAMPLE1/file3.bam:S1_REPLICATE3

A few more example are given here:
https://github.com/ablab/IsoQuant#examples

Best
Andrey

**Comment by andrewprzh** [comment]
@paulimer I'm very sorry for getting that late, could you re-upload the files if that's still possible?

Best
Andrey

**Comment by paulimer** [comment]
Thanks ! 
Oh `--label` was the part I was missing. Defaulting to the first file name made my file names a bit unwieldy.

**Comment by andrewprzh** [comment]
@paulimer 

I was able to reproduce the bug you reported previously concerning extended GTF annotation. It is now [fixed](https://github.com/ablab/IsoQuant/commit/f4fe9833473d572d258e2fd9a72276f4c03a3a22) in master and will be fixed in the next release. Thank you for reporting!

Best
Andrey

**Comment by andrewprzh** [comment]
The fix is now in IsoQuant 3.3.0.

Best
Andrey

**Comment by paulimer** [comment]
Great thank you very much ! I will test it as soon as possible, even though I noticed the issue only because I forgot to add the pathogen genome to my reference for alignment :laughing: .

**Comment by andrewprzh** [comment]
Turned out for good - this bug was a quite hard to notice otherwise.
