### ISSUE TITLE
installing problem

### ISSUE THREAD

**Issue by yidanma1998** [ablab/IsoQuant#71]
Hi, I tried installing isoquant on a cluster and had this error:

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.28=0
  - feature:|@/linux-64::__glibc==2.28=0

Your installed version is: 2.28

All requirements have been installed. What is the problem? Do you know how I can solve it?

Thank you so much!

**Comment by andrewprzh** [comment]
Dear @yidanma1998 

This looks like a conda / system problem, the only thing I can suggest right now is either to create a new conda environment or ask you system administrator. 

Best
Andrey

**Comment by yidanma1998** [comment]
Thank you, Andrey. Problem solved:)

Best,
Yidan

From: Andrey Prjibelski ***@***.***>
Date: Thursday, March 2, 2023 at 12:35 PM
To: ablab/IsoQuant ***@***.***>
Cc: Ma, Yidan ***@***.***>, Mention ***@***.***>
Subject: Re: [ablab/IsoQuant] installing problem (Issue #71)

Dear @yidanma1998<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_yidanma1998&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=XLJrLKAaCSYcz_B4nVtHKeT7KAJExoOtEL6g7Whx_6A&m=2eD0f_X5eQiAJtZyqtW5J0AdC3ygY4YaZfjIWA7tQSLGnRalKidpTkq2230k63Kq&s=T8QOlcZkhSYoCTiHffdMkaQ_2peU8fzQNwD4TJa6WNk&e=>

This looks like a conda / system problem, the only thing I can suggest right now is either to create a new conda environment or ask you system administrator.

Best
Andrey
