### ISSUE TITLE
how to extract reads that are full splice match and full length?

### ISSUE THREAD

**Issue by soniacruciani** [ablab/IsoQuant#74]
Hello, 
I have run Isoquant and filtered reads to have only full splice match reads. However, I realised those reads have all the right splice sites but can have different 3'-UTR lengths. So i.e. in the annotaion there is a long 3'-UTR, and reads with a shorter 3'-UTR are also considered the same transcript. 
Is there a way to filter reads that are not only full splice match but also full length? 
i.e. to also check for the read end to correspond to the transcript annotation end? 

Thanks!

**Comment by andrewprzh** [comment]
Dear @soniacruciani 

If a read has polyA tail, IsoQuant will report correct_polya_site is it matches the reference one.
However, no information is currently given for start/terminal positions. 

IsoQuant provides read coordinates in BED/TSV files, which allows you to check whether the assigned isoform has similar TSS/TES. I will consider adding this information in the future, e.g. report "TSS_match" if the read start has no more than 50 bp difference from the annotated TSS.

Best
Andrey

**Comment by soniacruciani** [comment]
Hi Andrey, 
Thanks for the quick response. 
I am confused about the polyA tail, I am working with Nanopore dRNA data, so the polyA is not encoded in the fastq... maybe this is a feature for other type of data? 

It would be great to implement the match with annotated TSS and TES, I think it would improve the annotations that Isoquant provides (right now it cannot distinguish between trasncripts that have different TES/TSS but matching all other EJs). 

Thanks again

Sonia

**Comment by andrewprzh** [comment]
Dear @soniacruciani 

IsoQuant 3.2 was just released, it now reports tss_match/tes_match for reads that have ends within 50bp of the assigned isoform ends, and tss_match_precise/tes_match_precise for accurate matches not exceeding delta bp (6 is default for ONT).

Best
Andrey

**Comment by soniacruciani** [comment]
Dear Andrey, 
Thanks for the quick implementation! 
Looking forward to trying it. 

Best, 

Sonia
