### ISSUE TITLE
questions about reads assignment

### ISSUE THREAD

**Issue by seven1112233** [ablab/IsoQuant#80]
Dear Andrey,
After quantifying transcripts with isoquant successfully, I merged transcript_model_reads.tsv, read_assignments.tsv with transcript_counts.tsv file. my aim is to extract some reads which contributed to transcript expression quantification. in next step, separate them into different isoform groups and comapre polyA tail length. however, i find that some reads with * transcript_id feature in transcript_model_reads.tsv but have good assignments annotation in read_assignments.tsv. could you tell me the reason?
for example:
![image](https://user-images.githubusercontent.com/71070001/227154056-8f819cf1-830e-484c-958e-065f22b4a376.png)

**Comment by andrewprzh** [comment]
Dear @seven1112233 

IsoQuant consists of 2 steps: 

1. Read assignment and quantification, which generates results only for known transcripts (read_assignments.tsv,  transcript_counts.tsv etc).
2. Transcript discovery, which creates a GTF with reliable known and novel isoforms, produces transcript_models.gtf, transcript_model_reads.tsv and transcript_model_counts.tsv.

If you are interested in annotated isoforms only, you can use read_assignments.tsv, since transcript_counts.tsv is based only on these assignments and represents only known transcripts. In this case, there is no need in using transcript_model_reads.tsv.

However, not all transcripts make to final GTF. IsoQuant is quite conservative, so even if a known isoform has a read assigned to it, it may not be enough for isoform to be considered as reliable. If you wish to include novel isoforms in your analysis, I suggest using transcript_model_reads.tsv and transcript_model_counts.tsv.

Best
Andrey

**Comment by seven1112233** [comment]
> 
I get it! its very nice of you! thank you very much!

**Comment by seven1112233** [comment]
Dear  Andrey,
your tools is very useful,
however, after running isoquant with: --gene_quantification all --no_secondary and default parameter; i get results files such as gene_counts.tsv and read_assignments.tsv. Though set --gene_quantification all, I find  some genes counts in gene_counts.tsv are inconsistent with the results in read_assignments.tsv. for example, for gene ENSG00000242028.8,there are 115 results in the read_assignments.tsv,as the figure shows some records, but in gene_counts.tsv, it only have 4.5 reads counts, could you tell me what happen?
![image](https://user-images.githubusercontent.com/71070001/228206689-ba2cdfe9-a78b-4507-8a93-d7dac95414ad.png)

**Comment by andrewprzh** [comment]
Dear @seven1112233 

That is, indeed, quite odd. Could you send me the IsoQuant log and a BAM file containing these 115 reads (e.g. a region corresponding to this gene)?

Best
Andrey

**Comment by andrewprzh** [comment]
Dear @seven1112233 

I checked this on some of my files, and I see that inconsistent reads are correctly used in gene quantification. However, reads that were ambiguously assigned to two or more genes are always ignored. This may happen even when secondary alignments are igonred, but the genes overlap.

I checked human gencode v35 annotation, this region does contain 4 overlapping genes:
ENSG00000262560.1 43772617 43799133
ENSG00000140264.20 43777087 43804427
ENSG00000184716.13 43794162 43800221
ENSG00000242028.8 43796142 43804427

So my guess is that these alignments could not be ambiguously assigned to a gene a thus are ignored in quantification.

Best
Andrey

**Comment by seven1112233** [comment]
Dear Andrey
here are the isoquant.log and&nbsp;bam file containing 115 reads.
thank you very much!&nbsp;




Dinasour
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ablab/IsoQuant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 晚上6:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ablab/IsoQuant] questions about reads assignment (Issue #80)





 
Dear @seven1112233
 
That is, indeed, quite odd. Could you send me the IsoQuant log and a BAM file containing these 115 reads (e.g. a region corresponding to this gene)?
 
Best
 Andrey

**Comment by seven1112233** [comment]
> Dear @seven1112233
> 
> I checked this on some of my files, and I see that inconsistent reads are correctly used in gene quantification. However, reads that were ambiguously assigned to two or more genes are always ignored. This may happen even when secondary alignments are igonred, but the genes overlap.
> 
> I checked human gencode v35 annotation, this region does contain 4 overlapping genes: ENSG00000262560.1 43772617 43799133 ENSG00000140264.20 43777087 43804427 ENSG00000184716.13 43794162 43800221 ENSG00000242028.8 43796142 43804427
> 
> So my guess is that these alignments could not be ambiguously assigned to a gene a thus are ignored in quantification.
> 
> Best Andrey
 Dear Andrey
however, records about these reads in read_assignments.tsv are inconsistent

**Comment by andrewprzh** [comment]
Dear @seven1112233 

If a read has several inconsistent assignments, they all still will be marked as inconsistent. 
Ambiguous reflects only multiple consistent assignments.

Best
Andrey

**Comment by seven1112233** [comment]
Dear Andrey
there are 115 reads in the file, but there only are 4.5 counts of the gene. so do it means that these reads assigned to more than 2 genes? Actually I remove all reads of supplementary and secondly alignments in my bam file which just contain reads with flag 0/16. could  isoqunat quantify gene counts according to the alignments infomation? that is, do not split reads between genes with equal weights
