### ISSUE TITLE
Issue with labeling samples multiple files

### ISSUE THREAD

**Issue by seungbeom-han** [ablab/IsoQuant#84]
I did not have this problem in the previous version, but the current version throws an error when I use multiple BAM files with labeling samples. For instance, running this raises an error.
```
isoquant.py --data_type nanopore --reference A.bam B.bam C.bam --labels A B C -o output
```
I've found that the variable `sample_files` is wrapped around an another list, so that its length is always zero. The variable `sample_files` in the example above would be `[[["A.bam"], ["B.bam"], ["C.bam"]]]`. 
I would be grateful if you tell me whether I had misunderstanding about IsoQuant or fix this issue.

**Comment by andrewprzh** [comment]
Dear @seungbeom-han 

The default behavior has changed in the new version 3.2.

Previously,  A, B, C would be treated as independent experiments and 3 independent GTF would be generated (each with the same label). Now, they are treated as different samples within the same experiment, and a single combined GTF is generated.

However, the `--labels` option still denotes experiment labels, not sample names. I will fix that.

To reproduce previous behavior you create a TXT file listing all files with blank lines between them:
```
A.bam

B.bam

C.bam
```
And provide it with `--bam_list`.

Best
Andrey

**Comment by seungbeom-han** [comment]
Thank you for informing about the change in version 3.2. This tool helped me a lot in data analysis and I appreciate you for maintaining this great program!
Now, I'll close the issue because all of the problems are solved.

**Comment by andrewprzh** [comment]
Thanks a lot for the positive feedback!
