### ISSUE TITLE
Failed Reference Indexing

### ISSUE THREAD

**Issue by BioinfoEurope** [ablab/IsoQuant#85]
Hello, 

I am trying to run Isoquant for long-read RNA sequencing (ONT), during the process 'Indexing reference',  I am getting the error : Failed indexing reference! 

My reference is human genome GRch38.p10.fasta. Can you please help me with this? 

Thank you

**Comment by andrewprzh** [comment]
Dear @BioinfoEurope 

Could you send me the isoquant.log please?
It seems like a problem with minimap2, which version do you have istalled?

Best
Andrey

**Comment by BioinfoEurope** [comment]
Dear Andrew, 
Thank you for your prompt response. 
I have resolved it, I found a few spaces in the file, and once I removed it, it was ok. 

Thank you

**Comment by andrewprzh** [comment]
Great to hear! Let me know if you have any other issues.

Best
Andrey
