### ISSUE TITLE
Computation of exon percentage spliced in or PSI

### ISSUE THREAD

**Issue by MiqG** [ablab/IsoQuant#89]
Hi, thank you for creating such a useful tool!

I would like to compute the percentage of inclusion for exons from long reads and wanted to make sure I understood correctly how I should do that with your software.

In the exon and intron count format table, there are the 
- `include_counts`: long reads that contain the exon
- and `exclude counts`: long reads that skip the exon

Then, the PSI in this case would be calculated just by computing:
$$PSI = \frac{includeCounts}{includeCounts + excludeCounts}$$

Is this correct?

Thanks very much in advance!

**Comment by andrewprzh** [comment]
Dear @MiqG 

Yes, you are right! These are numbers are given exactly for this purpose. I should probably include PSI itself in the next version :)

Best
Andrey
